"""C12b — Gate 2', the numerics gate re-based onto the frozen eager C++ engine.

WHAT REPLACED WHAT, AND WHY THAT IS NOT A LOOSENING
===================================================
Gate 2 asked whether the C++ gather reproduced ATen's priors to 1e-6 with no
ordering inversions. Inductor fuses bias/GELU/LayerNorm into the matmul epilogue.
It changes NO precision — the forward is bf16 before and after — but it changes
the ACCUMULATION ORDER, and a bf16 logit moved by one ulp moves a prior by ~1e-3,
three orders over that bound. So Gate 2 cannot be re-run against Python after
Inductor: it would fail, for a known and intended reason, and a gate that fails
for an intended reason teaches nothing.

The certification chain the C12b brief writes down instead:

    Python reference ──Gate 1 (bit-exact, replay)───► C++ tree logic
                     ──Gate 2 (<=1e-6, 0 inversions)► C++ eager forward
                     ──Gate 2b (497/500 = 99.4%)────► C++ eager engine
                                                            │
                                                       Gate 2' (HERE)
                                                            ▼
                                                       C++ Inductor engine

**Gate 1 is untouched and stays Python-anchored forever.** It runs the replay
evaluator with no network in the loop, so no forward change can reach it; Rule
2's golden data is network-free and nothing in this chunk affects it. That is the
fact that makes the move safe rather than a loosening. **Gate 2 and Gate 2b are
frozen as historical certifications and are not re-run** — C10's 497/500 stands
as the record that the C++ engine matches Python.

What this file compares against is `baseline/`, generated by
`tools/gen_c12b_baseline.py` from the eager engine at tag
GUOFISH_NUMERICS_BASELINE. That is C++ and torch output, so it is NOT golden data
and deliberately does not live in `golden/` (Global Rule 2).

THIS IS A MUCH LOOSER GATE THAN GATE 2 WAS, AND SAYING SO IS PART OF PASSING IT
==============================================================================
(And looser again than the C12b brief first drafted it — see `MIN_AGREEMENT`.)
A ~1e-3 prior perturbation is far larger than 1e-6. The honest claim this file
supports is **"the engine plays the same moves"**, not "the engine computes the
same numbers" — and the second is simply false, by design, which
`test_the_prior_shift_is_reported` prints in full rather than hides. Gate 5 is
what prices the difference in ELO.

**Inversions are measured, not gated.** The minimum inter-prior gap on this
corpus is 1.927e-06 (C10b), so a ~1e-3 shift inverts near-ties freely; a swap
between priors that close was arbitrary before the change too. What IS asserted
is that no inversion happens at a gap the measured shift could not have crossed,
which is a coherence check on the measurement rather than a bound on the engine.

WHAT IS ACTUALLY GATED HERE
===========================
  1. `compile=False` reproduces the frozen baseline BIT-EXACTLY, at every
     captured shape, on the raw bf16 words. The fallback is real or the whole
     chain has no anchor.
  2. Capture did not change the Inductor forward — captured replay against the
     un-captured compiled call, zero differing words.
  3. No dynamo frame is compiled after warmup, per captured shape.
  4. Priors are bit-identical across repeated runs, INCLUDING a fresh process.
  5. **>= 98%** move agreement against the frozen baseline.

The 98% is a ruled figure, not the brief's original 99%, and the near-tie
criterion the brief paired with it is now REPORTED rather than gated. Both moves
are the owner's, taken on evidence the harness cannot produce: the decisive
disagreements were adjudicated by hand against Stockfish at high depth and every
Inductor move came back equal or better. `MIN_AGREEMENT` carries the full
provenance, and `test_the_decisive_disagreements_are_listed_for_adjudication`
prints the list the next adjudication would work from. Nothing here was relaxed
to make a red suite green — the measurement is unchanged and is still printed in
full; what changed is which threshold the project decided it wanted.

Per Amendment D there are no module-scope skips. Every test is individually
marked and the reason names which of torch / CUDA / the checkpoint / the baseline
is missing, so a skipped platform reports a count and a reason rather than a
silent pass. **The Linux arm has no CUDA and certifies nothing in this file** —
C12's Amendment D note applies unchanged, and a green Linux run here means every
test skipped, not that Inductor was checked.
"""

import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
import time

import numpy as np
import pytest

import guofish_core

REPO_ROOT = Path(__file__).resolve().parent.parent

BASELINE_DIR = REPO_ROOT / "baseline"
FORWARD = (BASELINE_DIR / "c12b_eager_forward.npz", "GUOFISH_C12B_FORWARD")
SEARCH = (BASELINE_DIR / "c12b_eager_search.json", "GUOFISH_C12B_SEARCH")
MANIFEST = (BASELINE_DIR / "c12b_eager_manifest.json", "GUOFISH_C12B_MANIFEST")

CORPUS = REPO_ROOT / "golden" / "c10_corpus.json"
GATE1_MANIFEST = REPO_ROOT / "golden" / "gate1_manifest.json"

# THE 90M-CORPUS CHECKPOINT, i.e. `playing/v6/evaluator.py`'s `SHIPPING_MODEL`
# and the one `playv6.DEFAULT_MODEL` hands every tournament arm — NOT the 20M net
# that `evaluator.DEFAULT_MODEL` still points at for C10 and C10b's goldens.
# C12b is a throughput optimisation and a numerics re-baselining, so it is
# measured on the net that will be tuned and played.
# `test_the_two_model_constants_still_mean_what_they_say` keeps the split honest.
MODEL = REPO_ROOT / "models" / "guofish5_90M" / "v5_10.9M_best.pt"

DIGEST_TOOL = REPO_ROOT / "tools" / "c12b_forward_digest.py"

# GATE 2''s CRITERIA AS RULED, WHICH IS NOT AS THE BRIEF FIRST SET THEM.
#
# The C12b brief set ">= 99% move agreement, every disagreement traced to a
# near-tie (top-two visit margin < 2%)". Measured, the Inductor engine reached
# **98.65%** (513/520) at 1,600 simulations with 5 of 7 disagreements outside the
# 2% margin, and a full-corpus sweep at 6,400 made it **97.88%** — the divergence
# grows with search depth rather than converging. That was reported as a blocked
# gate with the criteria untouched (Global Rule 10), and the owner then ruled:
#
#   2026-08-13, owner: ~98% is sufficient. The five decisive disagreements listed
#   in BENCH.md C12b-6 were adjudicated by hand against Stockfish at high depth,
#   and EVERY Inductor move was equal to or better than the baseline's.
#
# **That ruling is a stronger test than the criterion it replaces, which is why
# it is a ruling and not a relaxation.** "Every disagreement is a near-tie" was
# only ever a PROXY for "the two engines do not disagree about the position" — it
# infers from visit margins that neither engine held a real opinion. Adjudicating
# the actual moves against a strong engine answers the underlying question
# directly, and it answered it in Inductor's favour. The proxy was in any case
# never satisfiable here: `tests/test_c10_gate2b.py::test_every_disagreement_is_a_near_tie`
# has been red since C10, between two engines that agree to 1e-6.
#
# So the agreement floor moves to 98% and the near-tie criterion becomes a
# REPORT rather than a gate — the same disposition the brief already gives prior
# inversions, and for the same reason.
#
# THE ADJUDICATION ITSELF IS NOT IN THIS REPOSITORY. It was performed by the
# owner outside the harness, so this file cannot re-derive it and does not claim
# to; what is recorded here is the ruling and its stated basis. A future chunk
# that wants the evidence back in the loop should add the Stockfish adjudication
# as a tool under `tools/` and cite its output.
MIN_AGREEMENT = 0.98
MAX_DISAGREEMENT_MARGIN = 0.02

# Matches tools/gen_c12b_baseline.py's FORWARD_MAX_BATCH; the captured ladder
# below max_batch is what the baseline recorded, so it has to be the same.
FORWARD_MAX_BATCH = 24


def _path(spec):
    default, env = spec
    return Path(os.environ.get(env, default))


# --- availability, resolved once and reported per test (Amendment D) --------

def _why_unavailable() -> str | None:
    """The reason Gate 2' cannot run here, or None.

    A guarded import plus a skipif marker, never a module-scope `importorskip` —
    the C7 incident was a module-scope skip silently taking 242 tests out of the
    Linux run while Global Rule 3 reported a pass.
    """
    try:
        import torch
    except Exception as exc:  # noqa: BLE001
        return f"torch is not importable ({type(exc).__name__}: {exc})"
    if not torch.cuda.is_available():
        return ("no CUDA device; Inductor emits Triton and the manual capture has "
                "no CPU equivalent, so this arm certifies nothing without a GPU")
    if not MODEL.exists():
        return f"the v5 checkpoint is missing ({MODEL})"
    for spec in (FORWARD, SEARCH, MANIFEST):
        if not _path(spec).exists():
            return (f"missing baseline artifact {_path(spec)}; generate it with "
                    f"python tools/gen_c12b_baseline.py")
    return None


UNAVAILABLE = _why_unavailable()
requires_inductor = pytest.mark.skipif(UNAVAILABLE is not None, reason=str(UNAVAILABLE))


# --- the baseline -----------------------------------------------------------

@pytest.fixture(scope="module")
def manifest():
    return json.loads(_path(MANIFEST).read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def baseline_forward():
    return np.load(_path(FORWARD), allow_pickle=False)


@pytest.fixture(scope="module")
def baseline_search():
    return json.loads(_path(SEARCH).read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def fens(baseline_forward):
    return [str(f) for f in baseline_forward["fens"]]


@pytest.fixture(scope="module")
def corpus_tokens(fens):
    return np.stack([guofish_core.tokens(fen) for fen in fens])


# --- the two evaluators -----------------------------------------------------

def _build(compiled: bool, max_batch: int = FORWARD_MAX_BATCH):
    from playing.v6 import evaluator as live_evaluator

    # The checkpoint is named, never defaulted — `build()`'s default is the 20M
    # net C10's goldens are anchored to, and every number in this file is about
    # the one the engine ships.
    return live_evaluator.build(max_batch, model_path=MODEL, compile=compiled)


@pytest.fixture(scope="module")
def inductor():
    """One Inductor evaluator for the module. Compiling is ~30 s cold; do it once."""
    built = _build(True)
    try:
        yield built
    finally:
        built.close()


def _sweep(evaluator, tokens, shape, rows):
    """`rows` positions through the PRODUCTION callback at exactly `shape`.

    Through `_evaluate` rather than around it, and in full blocks only, so no row
    is padding and every word compared is a word a real batch would have
    produced. This is the same blocking `tools/gen_c12b_baseline.py` recorded the
    baseline with; comparing a different blocking would measure the shape term
    (cuBLAS tiling) rather than the fusion term.
    """
    policy = np.zeros((rows, guofish_core.POLICY_SIZE), dtype=np.uint16)
    value = np.zeros(rows, dtype=np.float32)
    for start in range(0, rows, shape):
        evaluator._input_np[:shape] = tokens[start:start + shape]
        evaluator._evaluate(shape)
        policy[start:start + shape] = evaluator._policy_np[:shape]
        value[start:start + shape] = evaluator._value_np[:shape]
    return policy, value


@pytest.fixture(scope="module")
def inductor_priors(inductor, corpus_tokens, fens):
    """The production gather over logits INDUCTOR produced, at shape 1.

    Shape 1 because that is what the W=1/K=1 search below evaluates every batch
    at, so these are the priors Gate 2''s own move comparison actually saw.
    `guofish_core.gather_softmax` is the function the dispatcher calls, so this is
    the shipping path end to end: replay -> bf16 policy buffer -> the C++ gather.
    """
    policy, _ = _sweep(inductor, corpus_tokens, 1, len(fens))
    offsets = [0]
    rows = []
    for index, fen in enumerate(fens):
        uci, row = guofish_core.gather_softmax(fen, policy[index])
        rows.append(row)
        offsets.append(offsets[-1] + len(uci))
    return np.concatenate(rows).astype(np.float32), np.array(offsets, dtype=np.uint64)


# ---------------------------------------------------------------------------
# Provenance — the chain is only as good as the artifact
# ---------------------------------------------------------------------------

@requires_inductor
def test_the_baseline_is_the_tagged_eager_engine(manifest):
    """Requirement 1 of the freeze: a COMMIT, not "whatever eager does today".

    `head_is_tag` is the one that matters. A baseline generated from a tree that
    had already drifted off the tag would look identical to this one and would be
    certifying something nobody can check out again.
    """
    assert manifest["generator"] == "tools/gen_c12b_baseline.py"
    assert manifest["baseline_tag"] == "GUOFISH_NUMERICS_BASELINE"
    assert len(manifest["baseline_tag_sha"]) == 40, manifest["baseline_tag_sha"]
    assert manifest["head_is_tag"] is True, (
        f"the baseline was generated at {manifest['head_sha'][:12]}, which is not "
        f"{manifest['baseline_tag']} ({manifest['baseline_tag_sha'][:12]})")
    assert manifest["compile"] is False, (
        "the baseline records compile=True. A baseline generated through Inductor "
        "makes Gate 2' a comparison of Inductor against itself, which passes "
        "trivially and certifies nothing")
    assert manifest["corpus"]["positions"] == 520, manifest["corpus"]["positions"]


@requires_inductor
def test_the_baseline_artifacts_are_the_ones_the_manifest_digested(manifest):
    """Requirement 2: stored outputs, with byte-level provenance.

    The manifest's whole job is to make the arrays un-swappable. Checking the
    digests is what turns "the baseline is on disk" into "the baseline on disk is
    the one that was measured".
    """
    for name, spec in (("forward", FORWARD), ("search", SEARCH)):
        if _path(spec) != spec[0]:
            pytest.skip(f"{name} baseline overridden; digest not comparable")
        recorded = manifest["artifacts"][name]["sha256"]
        digest = hashlib.sha256(_path(spec).read_bytes()).hexdigest()
        assert digest == recorded, (
            f"baseline/{spec[0].name} has changed since the manifest was written\n"
            f"  manifest: {recorded}\n  on disk : {digest}")


@requires_inductor
def test_the_two_model_constants_still_mean_what_they_say():
    """C12b measures the SHIPPED net; C10 and C10b keep the one they were anchored to.

    `evaluator.DEFAULT_MODEL` is the 20M-corpus checkpoint because
    `golden/c10_gate2.npz` and `golden/c10_gate2b.json` record ITS priors and ITS
    moves, and those files come from the Python reference (Global Rule 2) and
    cannot be regenerated from a different net. `tests/test_c10_gate2b.py` and
    `tests/test_c10b_graphs.py` both call `build()` with no model, so repointing
    that constant would fail two historical certifications for a reason that has
    nothing to do with what they certify.

    `evaluator.SHIPPING_MODEL` is the 90M-corpus checkpoint — the same v5
    architecture, different weights — and it is what `playv6.DEFAULT_MODEL` hands
    every tournament arm. A throughput optimisation and a numerics re-baselining
    belong on the net that will be tuned and played, so everything in this file
    names it.

    Asserted rather than commented because the split is exactly the kind of thing
    that decays into an accident: if the two ever collapse onto one path, either
    C10b starts failing or C12b quietly stops measuring the shipped engine.
    """
    from playing.v6 import evaluator as live_evaluator
    from playing.v6.playv6 import DEFAULT_MODEL as ENGINE_MODEL

    assert live_evaluator.SHIPPING_MODEL == MODEL
    assert live_evaluator.SHIPPING_MODEL == ENGINE_MODEL, (
        f"the engine loads {ENGINE_MODEL} but C12b measured "
        f"{live_evaluator.SHIPPING_MODEL}; the optimisation and the shipped net "
        f"have come apart")
    assert live_evaluator.DEFAULT_MODEL != live_evaluator.SHIPPING_MODEL, (
        "DEFAULT_MODEL and SHIPPING_MODEL have collapsed onto one checkpoint. If "
        "that is deliberate, C10's and C10b's goldens no longer describe what "
        "build() loads and both suites are comparing a different network")
    assert live_evaluator.DEFAULT_MODEL.parent.name == "guofish5_20M"
    assert live_evaluator.SHIPPING_MODEL.parent.name == "guofish5_90M"


@requires_inductor
def test_the_baseline_ran_the_checkpoint_that_is_on_disk(manifest):
    """A differential against a different network measures nothing."""
    digest = hashlib.sha256(MODEL.read_bytes()).hexdigest()
    assert digest == manifest["model"]["sha256"], (
        f"the checkpoint on disk is not the one the baseline ran.\n"
        f"  manifest: {manifest['model']['sha256']}\n  on disk : {digest}")


@requires_inductor
def test_the_corpus_is_gate_2bs_plus_the_gate_1_position_set(manifest, fens):
    """The brief names Gate 2''s corpus exactly; this is the check that it is that.

    Both digests, because the union is the corpus and either half changing
    changes it. The disjointness is enforced by the generator — a duplicated FEN
    would be counted twice in the agreement rate — and the count is what shows it
    held.
    """
    assert manifest["corpus"]["c10_corpus"]["sha256"] == \
        hashlib.sha256(CORPUS.read_bytes()).hexdigest()
    assert manifest["corpus"]["gate1"]["sha256"] == \
        hashlib.sha256(GATE1_MANIFEST.read_bytes()).hexdigest()
    assert manifest["corpus"]["c10_corpus"]["positions"] == 500
    assert manifest["corpus"]["gate1"]["positions"] == 20
    assert len(fens) == 520
    assert len(set(fens)) == 520, "the two position sets overlap"


# ---------------------------------------------------------------------------
# Acceptance 5 — the eager fallback is real
# ---------------------------------------------------------------------------

@requires_inductor
def test_compile_false_reproduces_the_frozen_baseline_bit_exactly(corpus_tokens, fens,
                                                                 baseline_forward,
                                                                 capsys):
    """`compile=False` still IS the frozen baseline — raw bf16 words, every shape.

    THE ANCHOR OF THE WHOLE CHAIN. Gate 2' compares Inductor against the baseline
    artifact; that comparison only means anything if the baseline artifact is
    still reachable from this working tree. If this test fails, the eager path has
    drifted since the tag and every other number in this file is measuring the
    drift as well as the fusion.

    Compared on the WORDS rather than on the priors: a prior is a softmax over the
    ~30 legal columns of a 4096-wide row, so a logit the gather never reads could
    move without moving any prior.
    """
    evaluator = _build(False)
    lines = []
    try:
        assert evaluator.compiled is False
        for shape in evaluator.graph_sizes:
            want_policy = baseline_forward[f"policy_{shape}"]
            want_value = baseline_forward[f"value_{shape}"]
            rows = want_policy.shape[0]
            assert rows == (len(fens) // shape) * shape
            got_policy, got_value = _sweep(evaluator, corpus_tokens, shape, rows)
            bad_policy = int((got_policy != want_policy).sum())
            bad_value = int((got_value != want_value).sum())
            lines.append(f"  shape {shape:>3}: {rows:>4} positions, "
                         f"{bad_policy} of {want_policy.size:,} policy words differ, "
                         f"{bad_value} values")
            assert bad_policy == 0, (
                f"compile=False no longer reproduces tag GUOFISH_NUMERICS_BASELINE "
                f"at shape {shape}: {bad_policy} of {want_policy.size} bf16 policy "
                f"words differ. The eager path has drifted since the tag, so the "
                f"baseline every other test here compares against is stale.")
            assert bad_value == 0, (
                f"{bad_value} values differ from the frozen baseline at shape {shape}")
    finally:
        evaluator.close()
    with capsys.disabled():
        print("\nC12b — compile=False against the frozen eager baseline")
        print("\n".join(lines))


# ---------------------------------------------------------------------------
# Capture fidelity, and the recompilation guard
# ---------------------------------------------------------------------------

@requires_inductor
def test_the_manual_capture_did_not_change_the_inductor_forward(inductor, corpus_tokens,
                                                                capsys):
    """Capture is a no-op on the numerics; fusion is not. This separates them.

    The brief's hazard 1 is that Inductor and the manual capture will fight if
    they are allowed to — `mode="reduce-overhead"` brings compile-owned cudagraph
    trees, which would orphan every C10b shape and staleness drill. C12b ships
    default mode captured by the existing machinery instead, and this is the
    evidence the combination is sound: captured replay against the un-captured
    compiled call, at every shape, zero differing words.

    If this ever fails, the agreement rate below is not interpretable whatever it
    prints, because the two arms would then be different forwards for a second,
    unintended reason.
    """
    import torch

    graph = inductor.graph
    lines = []
    for shape in graph.sizes:
        rows = (len(corpus_tokens) // shape) * shape
        bad = 0
        for start in range(0, rows, shape):
            got, _ = _sweep(inductor, corpus_tokens[start:start + shape], shape, shape)
            want, _ = graph.eager(shape)
            torch.cuda.synchronize()
            bad += int((got != want.view(torch.uint16).cpu().numpy()).sum())
        lines.append(f"  shape {shape:>3}: {bad} differing policy words over "
                     f"{rows} positions")
        assert bad == 0, (
            f"the captured Inductor graph disagrees with the un-captured compiled "
            f"call at shape {shape} ({bad} words). That is a CAPTURE defect, not "
            f"the fusion re-baselining this chunk is about.")
    with capsys.disabled():
        print("\nC12b capture fidelity (captured replay vs un-captured compiled call)")
        print("\n".join(lines))


@requires_inductor
def test_warmup_converged_before_anything_was_captured(inductor):
    """Brief hazard 2: a recompilation during capture would be silent and fatal.

    `_warm_to_convergence` runs whole warmup rounds until a round adds no dynamo
    frame, so two rounds is the floor — the first compiles, the second confirms.
    Fewer than two would mean the convergence check never actually ran; the frame
    delta equalling the shape count is the other half, and says each shape
    compiled exactly one frame rather than one shape compiling several.
    """
    graph = inductor.graph
    assert set(graph.warmup_rounds) == set(graph.sizes)
    for shape, rounds in graph.warmup_rounds.items():
        assert rounds >= 2, (
            f"shape {shape} converged in {rounds} round(s); the confirming round "
            f"never ran, so convergence was assumed rather than observed")

    # THE RECOMPILE LIMIT, WHICH IS A SHIPPED-CONFIG BUG THIS CHUNK FOUND.
    # `torch._dynamo`'s default is 8; the shipping ladder is nine shapes and
    # `dynamic=False` makes each one its own frame, so the ninth blew the limit
    # and dynamo silently ran shape 128 EAGER — the engine's `max_batch`. It was
    # visible only as a throughput row measuring exactly 1.000x with 0 of 524,288
    # policy words differing.
    assert graph.recompile_limit >= len(graph.sizes), (
        f"dynamo's recompile limit is {graph.recompile_limit} for "
        f"{len(graph.sizes)} captured shapes; the largest shapes will fall back "
        f"to eager instead of compiling")

    # And the property the limit exists to protect, asked of every shape directly
    # rather than inferred from a counter. Counting compiled frames cannot answer
    # this: a shape that hit the limit stops compiling and so converges
    # immediately, and a second `torch.compile` of the same module in one process
    # reuses dynamo's cache and legitimately compiles nothing.
    graph.assert_every_shape_is_fused()


@requires_inductor
def test_no_dynamo_frame_is_compiled_after_warmup(inductor, corpus_tokens):
    """Acceptance 4, driven through the production callback at every width.

    Not only at the captured shapes: `pad_to` means a batch of 21 runs at shape
    24, so every count in [1, max_batch] is a width the dispatcher can hand over
    and none of them may reach the compiler. A recompilation mid-search is a
    multi-second stall that reads as a hung engine — and inside a capture it is
    worse than a stall.
    """
    from playing.v6.graphs import dynamo_frame_count

    before = dynamo_frame_count()
    for count in range(1, inductor.max_batch + 1):
        inductor._input_np[:count] = corpus_tokens[:count]
        inductor._evaluate(count)
    assert dynamo_frame_count() == before, (
        f"driving counts 1..{inductor.max_batch} through the callback compiled "
        f"{dynamo_frame_count() - before} dynamo frame(s)")
    inductor.assert_no_recompilation("after sweeping every dispatchable width")


# ---------------------------------------------------------------------------
# Acceptance 3 — determinism, and what pins it
# ---------------------------------------------------------------------------

@requires_inductor
def test_autotuning_is_off_because_that_is_what_pins_the_kernels(inductor):
    """The brief asks the autotune cache to be pinned. C12b removes it instead.

    Left on, Inductor benchmarks several Triton configs per pointwise/reduction
    kernel at first call and caches the winner in a `.best_config` file. The
    winner comes from measured times, so it varies with GPU clock and machine
    load: **17 of 28 `.best_config` files differ between two cold compiles of this
    model**, and a reduction kernel's block size changes the accumulation order,
    which changes the bits.

    Turned off, the heuristics emit one config per kernel and ZERO `.best_config`
    files are written — so there is no cache to pin, nothing keyed on the GPU,
    driver or torch version, and nothing to go stale. It is asserted here rather
    than only recorded in DECISIONS.md because it is the mechanism the two
    determinism tests below depend on, and a future torch that changes the
    default would otherwise break them with no explanation attached.
    """
    import torch._inductor.config as inductor_config

    assert inductor.graph.inductor_settings == {
        "use_static_cuda_launcher": False, "triton.autotune_pointwise": False}
    assert inductor_config.triton.autotune_pointwise is False
    # Not a preference: with torch 2.8.0+cu129 / triton 3.4.0 on this device the
    # static launcher raises OverflowError on the first Inductor kernel.
    assert inductor_config.use_static_cuda_launcher is False


@requires_inductor
def test_a_second_capture_in_this_process_agrees_bit_for_bit(inductor, corpus_tokens,
                                                             fens):
    """Same code, same GPU, same driver — twice — must be the same bits.

    A fresh `TorchEvaluator` re-runs warmup and re-captures every shape, so this
    exercises the capture path rather than replaying the graphs already built.
    It is the weaker of the two determinism checks, because both captures share
    one interpreter's compile cache and loaded Triton binaries; the subprocess
    test below is the one that closes that.
    """
    shape = FORWARD_MAX_BATCH
    rows = (len(fens) // shape) * shape
    first, first_value = _sweep(inductor, corpus_tokens, shape, rows)
    second_evaluator = _build(True)
    try:
        second, second_value = _sweep(second_evaluator, corpus_tokens, shape, rows)
    finally:
        second_evaluator.close()
    assert np.array_equal(first, second), (
        f"two captures in one process disagree on "
        f"{int((first != second).sum())} of {first.size} policy words")
    assert np.array_equal(first_value, second_value)


@requires_inductor
def test_a_fresh_process_reproduces_the_priors_bit_for_bit(inductor, corpus_tokens,
                                                           fens, capsys):
    """The determinism criterion as the brief states it: across RUNS.

    A run is a process. Two captures in one interpreter share the compile cache,
    the loaded Triton binaries, the cuBLAS handles and the allocator's arenas, so
    agreeing with itself is a much weaker claim than agreeing with a process that
    started cold — and it is the weaker claim an in-test loop would be making.

    SPSA tuning is next, and a nondeterministic engine makes every subsequent
    measurement noisier; the brief says stop and report rather than ship one.
    """
    completed = subprocess.run(
        [sys.executable, str(DIGEST_TOOL), "--compile",
         "--max-batch", str(FORWARD_MAX_BATCH)],
        capture_output=True, text=True, cwd=str(REPO_ROOT))
    assert completed.returncode == 0, (
        f"the digest tool failed:\n{completed.stdout[-2000:]}\n{completed.stderr[-2000:]}")
    marker = "C12B_FORWARD_DIGEST "
    payloads = [line for line in completed.stdout.splitlines() if line.startswith(marker)]
    assert payloads, f"no digest in the tool's output:\n{completed.stdout[-2000:]}"
    fresh = json.loads(payloads[-1][len(marker):])
    assert fresh["compile"] is True

    lines = []
    for shape in inductor.graph_sizes:
        rows = (len(fens) // shape) * shape
        policy, value = _sweep(inductor, corpus_tokens, shape, rows)
        here = hashlib.sha256(policy.tobytes()).hexdigest()
        there = fresh["shapes"][str(shape)]["policy_sha256"]
        lines.append(f"  shape {shape:>3}: {here[:24]} vs {there[:24]}  "
                     f"{'same' if here == there else 'DIFFER'}")
        assert here == there, (
            f"a fresh process produced different priors at shape {shape}.\n"
            f"  this process : {here}\n  fresh process: {there}\n"
            f"Determinism is the property most at risk in this chunk and the one "
            f"worth most; the brief says stop and report rather than ship without it.")
        assert hashlib.sha256(value.tobytes()).hexdigest() == \
            fresh["shapes"][str(shape)]["value_sha256"]
    with capsys.disabled():
        print("\nC12b determinism — policy digests, this process vs a fresh one")
        print("\n".join(lines))
        print(f"  fresh process ran on {fresh['provenance']['cuda_device']}, "
              f"torch {fresh['provenance']['torch']}")


# ---------------------------------------------------------------------------
# The re-baselining itself — measured and reported, not gated
# ---------------------------------------------------------------------------

@requires_inductor
def test_the_prior_shift_is_reported(inductor_priors, baseline_forward, fens, capsys):
    """How far Inductor moved the priors. REPORTED — this is not a bound.

    The brief is explicit that Gate 2' is a much looser gate than Gate 2 was and
    that saying so is part of passing it. Gate 2's bound was 1e-6; what is printed
    here is three orders larger, and that is the intended consequence of fusing
    the epilogues, not a defect.

    What IS asserted is only that the comparison is coherent: the priors are
    finite and still sum to 1 per position. A NaN or a broken softmax would
    otherwise sail through a test whose headline number is "reported".
    """
    got, offsets = inductor_priors
    want = baseline_forward["priors"]
    want_offsets = baseline_forward["move_offset"]
    assert np.array_equal(offsets, want_offsets), (
        "the two engines gathered different move lists; the priors are not "
        "element-wise comparable and every number below would be meaningless")

    deltas = np.abs(got.astype(np.float64) - want.astype(np.float64))

    # THE ARM UNDER TEST IS ACTUALLY THE FUSED ONE. Everything else in this file
    # would pass if `compile=True` silently produced the eager forward: the
    # capture-fidelity comparison would be eager-against-eager, the determinism
    # checks would agree trivially, and Gate 2' would report 100% move agreement
    # against a baseline it had merely reproduced. That is the self-comparison
    # trap the brief calls the worst available outcome, and this is the assertion
    # that makes it impossible — a genuinely fused forward moves ~60% of the bf16
    # policy words, so bit-identical priors here mean Inductor never ran.
    assert deltas.max() > 0.0, (
        "the Inductor arm's priors are bit-identical to the frozen EAGER "
        "baseline's at every one of the corpus's priors. Inductor is not running, "
        "so Gate 2' is comparing the baseline against itself and every result in "
        "this file is vacuous.")

    per_position_linf, per_position_l1 = [], []
    for i in range(len(fens)):
        begin, end = int(offsets[i]), int(offsets[i + 1])
        block = deltas[begin:end]
        per_position_linf.append(float(block.max()) if block.size else 0.0)
        per_position_l1.append(float(block.sum()))
        total = float(got[begin:end].sum())
        assert np.isfinite(total) and abs(total - 1.0) < 1e-4, (
            f"the Inductor priors at {fens[i]} sum to {total}, not 1")

    linf = np.array(per_position_linf)
    l1 = np.array(per_position_l1)
    with capsys.disabled():
        print("\nC12b — Gate 2' prior shift, Inductor against the frozen eager baseline")
        print(f"  {deltas.size:,} priors over {len(fens)} positions; "
              f"{int((deltas == 0).sum()):,} bit-identical "
              f"({100 * (deltas == 0).mean():.1f}%)")
        print(f"  |dprior| overall : max {deltas.max():.3e}  "
              f"p99 {np.percentile(deltas, 99):.3e}  "
              f"median {np.median(deltas):.3e}")
        print(f"  per-position Linf: max {linf.max():.3e}  "
              f"p99 {np.percentile(linf, 99):.3e}  median {np.median(linf):.3e}  "
              f"min {linf.min():.3e}")
        print(f"  per-position L1  : max {l1.max():.3e}  "
              f"p99 {np.percentile(l1, 99):.3e}  median {np.median(l1):.3e}")
        print(f"  for scale, Gate 2's bound was 1e-06 and this is "
              f"{deltas.max() / 1e-6:,.0f}x it — by design, not by defect")


@requires_inductor
def test_the_inversion_rate_is_reported(inductor_priors, baseline_forward, fens, capsys):
    """Prior-ordering inversions: measured, with the margin distribution. Not gated.

    Gate 2 gated inversions at zero because PUCT reads priors only through
    comparisons, so a reversed pair changes which child is selected. That bound
    cannot survive a ~1e-3 shift: the minimum inter-prior gap on this corpus is
    1.927e-06 (C10b), so near-ties invert freely — and a swap between priors that
    close was arbitrary before the change too.

    The one thing asserted is a COHERENCE check, not a bound on the engine: if
    every prior moved by at most `delta`, then a pair can only swap order if its
    baseline gap was at most `2 * delta`. An inversion at a wider gap would mean
    the two arrays are not the same 520 positions in the same order, which is a
    bug in this test rather than a finding about Inductor.
    """
    got, offsets = inductor_priors
    want = baseline_forward["priors"]
    delta = float(np.abs(got.astype(np.float64) - want.astype(np.float64)).max())
    reachable = 2 * delta

    inversions = 0
    pairs = 0
    gaps = []
    worst = None
    for i in range(len(fens)):
        begin, end = int(offsets[i]), int(offsets[i + 1])
        ref = want[begin:end].astype(np.float64)
        new = got[begin:end].astype(np.float64)
        if ref.size < 2:
            continue
        sign_ref = np.sign(ref[:, None] - ref[None, :])
        sign_new = np.sign(new[:, None] - new[None, :])
        inverted = np.triu(sign_ref * sign_new, 1) < 0
        pairs += ref.size * (ref.size - 1) // 2
        count = int(inverted.sum())
        if count:
            inversions += count
            gap = np.abs(ref[:, None] - ref[None, :])[inverted]
            gaps.append(gap)
            if worst is None or gap.max() > worst[1]:
                worst = (fens[i], float(gap.max()))

    gap_all = np.concatenate(gaps) if gaps else np.zeros(0)
    with capsys.disabled():
        print("\nC12b — Gate 2' prior-ordering inversions (measured, not gated)")
        print(f"  {inversions:,} inverted pairs of {pairs:,} comparable "
              f"({100 * inversions / max(1, pairs):.3f}%)")
        if gap_all.size:
            print(f"  baseline gap at an inverted pair: max {gap_all.max():.3e}  "
                  f"p99 {np.percentile(gap_all, 99):.3e}  "
                  f"median {np.median(gap_all):.3e}  min {gap_all.min():.3e}")
            print(f"  widest: {worst[1]:.3e} at {worst[0]}")
        print(f"  max |dprior| is {delta:.3e}, so no pair wider than "
              f"{reachable:.3e} can invert")

    if gap_all.size:
        assert gap_all.max() <= reachable * 1.000001, (
            f"an inverted pair had a baseline gap of {gap_all.max():.6e}, wider "
            f"than 2 x max|dprior| = {reachable:.6e} could cross. The two prior "
            f"arrays are not the same positions in the same order.")


# ---------------------------------------------------------------------------
# Gate 2' — the move agreement criterion
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def differential(baseline_search):
    """The Inductor engine over every recorded position. One sweep, four tests.

    W=1, K=1: one search thread, one in-flight path — the configuration the
    baseline ran and the one the criterion's "1 thread" names. With a single
    simulation in flight, virtual loss is applied during a descent and repaid
    before the next one starts, so it never influences a selection on either
    side and drops out of the comparison entirely.

    Every search parameter comes from the baseline's own record rather than from
    this file's defaults. That is not defensiveness: the first run of Gate 2b
    took `SearchConfig()`'s `virtual_loss=0.0` against the reference's 2.5,
    nothing complained, and the result was twelve DECISIVE disagreements that
    looked like a broken evaluator and were two engines running two different
    searches.
    """
    recorded = baseline_search["search_config"]
    config = guofish_core.SearchConfig()
    config.c_init = recorded["c_init"]
    config.c_base = recorded["c_base"]
    config.fpu_root = recorded["fpu_root"]
    config.fpu_tree = recorded["fpu_tree"]
    config.virtual_loss = recorded["virtual_loss"]
    config.max_tree_depth = recorded["max_tree_depth"]
    config.cache_slots = baseline_search["cache_slots"]

    evaluator = _build(True, baseline_search["max_batch"])
    search = guofish_core.ReplaySearchDouble(config)
    search.set_evaluator(evaluator.core)
    parallel = guofish_core.ParallelConfig(workers=1, in_flight=baseline_search["in_flight"],
                                           max_batch=baseline_search["max_batch"])
    sims = baseline_search["sims"]

    results = []
    started = time.perf_counter()
    total = len(baseline_search["records"])
    try:
        for index, record in enumerate(baseline_search["records"]):
            # RUN WITH `-s` TO SEE THIS LIVE. pytest's default fd-level capture
            # swallows stdout and stderr until the test ends, so a silent sweep is
            # indistinguishable from a hung one without the flag.
            if index and index % 50 == 0:
                rate = index / (time.perf_counter() - started)
                print(f"  gate2' {index}/{total}  {rate:.2f} pos/s  "
                      f"eta {(total - index) / rate:.0f}s", flush=True)
            search.set_position(record["fen"])
            stats = search.search_parallel(sims, parallel)
            arrays = search.dump_tree_arrays(0)
            visits = {guofish_core.move_to_uci(int(move)): int(count)
                      for depth, move, count in zip(arrays["depth"], arrays["move"],
                                                    arrays["visits"]) if depth == 1}
            counts = sorted(visits.values(), reverse=True)
            total_visits = sum(counts)
            margin = (1.0 if len(counts) == 1 else
                      (counts[0] - counts[1]) / total_visits if total_visits else 0.0)
            results.append({
                "fen": record["fen"],
                "source": record["source"],
                "baseline_move": record["best_move"],
                "engine_move": stats["best_move"],
                "baseline_margin": record["margin"],
                "engine_margin": margin,
                "baseline_visits": record["visits"],
                "engine_visits": visits,
                "root_visits": int(stats["root_visits"]),
                "baseline_root_visits": record["root_visits"],
                "mating_move": stats["mating_move"],
                "baseline_mating_move": record["mating_move"],
            })
        evaluator.assert_no_recompilation("over the whole Gate 2' sweep")
    finally:
        search.set_evaluator(None)
        evaluator.close()
    return results, time.perf_counter() - started, sims


@requires_inductor
def test_every_search_delivered_the_budget(differential):
    """Before agreement is compared, both arms must have run the same search.

    The root ends at exactly `sims` visits unless the depth-1 mate short-circuit
    fired, which ends the search early on both sides by design — so those
    positions are exempted by name rather than by tolerance, and the exemption is
    checked to be the SAME positions on both arms.
    """
    results, _, sims = differential
    short = [r for r in results if r["mating_move"] is not None]
    for record in results:
        assert (record["mating_move"] is None) == (record["baseline_mating_move"] is None), (
            f"{record['fen']}: the mate short-circuit fired on one arm and not the "
            f"other (baseline {record['baseline_mating_move']}, engine "
            f"{record['mating_move']}), so the two searches are not comparable")
        if record["mating_move"] is not None:
            continue
        assert record["root_visits"] == sims, (
            f"{record['fen']} ran {record['root_visits']} simulations, not {sims}")
        assert record["baseline_root_visits"] == sims
    if short:
        print(f"\n{len(short)} positions ended on the depth-1 mate short-circuit "
              f"(exempt from the budget check on both arms)")


@requires_inductor
def test_move_agreement_against_the_baseline_meets_the_ruled_floor(
        differential, capsys):
    """Gate 2', criterion 1, with every disagreement printed.

    NAMED FOR THE FLOOR RATHER THAN FOR A NUMBER, because the number moved once
    already: this was `..._on_99_percent_of_moves` until the owner ruled 98%, at
    which point the name was the only thing still asserting 99. `MIN_AGREEMENT`
    is the single place the figure lives.

    This is the substantive claim of the chunk: **the engine plays the same
    moves**. It is not, and does not pretend to be, a claim that it computes the
    same numbers — `test_the_prior_shift_is_reported` prints how far from true
    that is.
    """
    results, seconds, sims = differential
    disagreements = [r for r in results if r["engine_move"] != r["baseline_move"]]
    agreed = len(results) - len(disagreements)
    rate = agreed / len(results)

    with capsys.disabled():
        print()
        print(f"Gate 2' — {len(results)} positions at {sims} sims, W=1 K=1, "
              f"Inductor engine vs frozen eager baseline, {seconds:.0f}s")
        print(f"  agreement: {agreed}/{len(results)} = {rate:.4%}  "
              f"(criterion >= {MIN_AGREEMENT:.0%})")
        by_source = {}
        for record in results:
            hit, seen = by_source.get(record["source"], (0, 0))
            by_source[record["source"]] = (
                hit + (record["engine_move"] == record["baseline_move"]), seen + 1)
        for source, (hit, seen) in sorted(by_source.items()):
            print(f"    {source:12s} {hit}/{seen} = {hit / seen:.2%}")
        if disagreements:
            print(f"  {len(disagreements)} disagreements:")
            for record in disagreements:
                base, eng = record["baseline_move"], record["engine_move"]
                print(f"    {record['fen']}  [{record['source']}]")
                print(f"      baseline {base:6s} "
                      f"(its visits: {record['baseline_visits'].get(base, 0)}"
                      f" vs {record['baseline_visits'].get(eng, 0)} for {eng})"
                      f"  margin {record['baseline_margin']:.4%}")
                print(f"      inductor {eng:6s} "
                      f"(its visits: {record['engine_visits'].get(eng, 0)}"
                      f" vs {record['engine_visits'].get(base, 0)} for {base})"
                      f"  margin {record['engine_margin']:.4%}")
        else:
            print("  no disagreements")

    assert rate >= MIN_AGREEMENT, (
        f"move agreement {rate:.4%} is below the {MIN_AGREEMENT:.0%} criterion "
        f"({len(disagreements)} disagreements over {len(results)} positions); each "
        f"one is printed above with both moves and both margins")


@requires_inductor
def test_the_decisive_disagreements_are_listed_for_adjudication(differential, capsys):
    """The near-tie split — REPORTED, not gated. See MIN_AGREEMENT for the ruling.

    The brief gated this: every disagreement had to sit under a 2% top-two visit
    margin. It does not, it never did on this corpus, and the criterion turned out
    to be measuring the wrong thing twice over.

    **It is not satisfiable even at 1e-6.**
    `tests/test_c10_gate2b.py::test_every_disagreement_is_a_near_tie` has been red
    since C10 on this same corpus, between the Python reference and the C++ engine
    — two forwards whose priors agree to a millionth. One of its two decisive
    positions, `2R5/7p/P3k3/1PK2p1p/5P1P/8/8/2r5 w - - 1 49`, reappears in C12b's
    own list with the two arms landing on the two sides of it. A bound that a
    1e-6 difference already breaks says nothing about a 1e-3 one.

    **And it was only ever a proxy.** A small visit margin is evidence that
    neither engine held a real opinion; what anyone actually wants to know is
    whether the moves are worse. The owner answered that directly — every
    Inductor move among the decisive disagreements was adjudicated equal or
    better against Stockfish at high depth — which is why this is now a list
    printed FOR adjudication rather than a threshold pretending to perform it.

    So this test fails only if the sweep itself is incoherent. The margins are
    printed, in full, so a reader can adjudicate the next run the same way.
    """
    results, _, _ = differential
    disagreements = [r for r in results if r["engine_move"] != r["baseline_move"]]
    decisive = [r for r in disagreements
                if r["baseline_margin"] >= MAX_DISAGREEMENT_MARGIN
                or r["engine_margin"] >= MAX_DISAGREEMENT_MARGIN]

    with capsys.disabled():
        print(f"\n  {len(disagreements)} disagreement(s), {len(decisive)} outside the "
              f"{MAX_DISAGREEMENT_MARGIN:.0%} near-tie margin (reported, not gated):")
        for record in decisive:
            print(f"    {record['fen']}")
            print(f"      baseline {record['baseline_move']:6s} "
                  f"(margin {record['baseline_margin']:7.3%})   "
                  f"inductor {record['engine_move']:6s} "
                  f"(margin {record['engine_margin']:7.3%})")
        if not decisive:
            print("    none — every disagreement was a near-tie this run")

    # The only assertion left is a coherence one: a "disagreement" must actually
    # be two different legal moves, and both arms must have produced a move. If
    # that breaks, the sweep is malformed and every number above is meaningless.
    for record in disagreements:
        assert record["baseline_move"] and record["engine_move"], record["fen"]
        assert record["baseline_move"] != record["engine_move"], record["fen"]


@requires_inductor
def test_the_margin_distribution_explains_the_agreement_rate(differential, capsys):
    """Reported, not asserted: how much of the corpus was ever in doubt.

    Agreement is bounded above by the fraction of positions whose top-two margin
    leaves room to differ, so printing that fraction is what makes the rate
    interpretable. 99% over a corpus where 30% of positions are near-ties would be
    a far stronger result than the same number where 1% are.
    """
    results, _, _ = differential
    near = [r for r in results if r["baseline_margin"] < MAX_DISAGREEMENT_MARGIN]
    disagreed_near = [r for r in near if r["engine_move"] != r["baseline_move"]]
    outside = sum(1 for r in results
                  if r["engine_move"] != r["baseline_move"]) - len(disagreed_near)
    with capsys.disabled():
        print(f"  positions the baseline decided by < {MAX_DISAGREEMENT_MARGIN:.0%}: "
              f"{len(near)}/{len(results)} = {len(near) / len(results):.2%}")
        print(f"  of those, disagreed: {len(disagreed_near)}/{len(near)}")
        print(f"  disagreements outside that set: {outside}")
