"""TM — the time manager. Parts 0, 1, 2 and 3.

The brief is `docs/TC/tc_manager_brief.md`; the constants it is written against
are `docs/TC/TM_CONSTANTS.md`, regenerated by
`telemetry/fit_tm_constants.py` from data already on disk.

WHAT EACH PART HAS TO PROVE HERE, AND WHAT IT CANNOT
====================================================

  Part 0  the constants the engine carries are the constants that were fitted.
          A module that drifts from its own fit is the failure this file's
          first section exists to catch, and it is checked against the JSON the
          fit writes rather than against a number retyped here.

          MEAN-NEUTRALITY IS ASSERTED, NOT ASSUMED. `ANALYSIS.md` §4a asks for
          `E[m]` to be reported next to any proposed multiplier set; here it is
          a test, computed over the frequencies F3 measured.

  Part 1  the control law, which is pure arithmetic and therefore fully
          testable: the estimator and its floor, the reserve, the emergency,
          the 40% clamp, the per-bucket nps smoother, and the one evaluation at
          the smart-pruning floor with its three outcomes.

          What is NOT here: whether the allocation is any good. That is
          `telemetry/tm_replay.py` over eighty recorded games, and after it the
          shadow week.

  Part 2  the four rows of the switch table, at the planner level. Off means
          the planner returns what it returned before, which is asserted by
          calling it both ways on the same inputs rather than by remembering
          what it used to say.

  Part 3  shadow mode is computed and ignored — the hook returns None on every
          call with the switch off — and the record carries the eight fields
          the brief names.

AMENDMENT D: no module-scope skip. `playing.v6.time_manager` imports only the
standard library, so the Part 0/1 tests always run; the wrapper tests carry
their own marker.
"""
from __future__ import annotations

import json
import math
import sys
import time
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from playing.v6.time_manager import (  # noqa: E402
    DEFAULT_CONSTANTS, MULTIPLIERS, NPS_BUCKETS, TMConstants, TMPlan,
    TimeManager,
)

CONSTANTS_JSON = REPO_ROOT / "runs/TM/tm_constants.json"


def _why_no_wrapper() -> str | None:
    try:
        import chess  # noqa: F401 - probing importability
    except ImportError as exc:
        return f"python-chess is not importable ({exc})"
    try:
        import playing.uci_wrapper_v6  # noqa: F401 - probing importability
    except ImportError as exc:                     # pragma: no cover - diagnostic
        return f"playing.uci_wrapper_v6 is not importable ({exc})"
    return None


WRAPPER_UNAVAILABLE = _why_no_wrapper()
requires_wrapper = pytest.mark.skipif(WRAPPER_UNAVAILABLE is not None,
                                      reason=str(WRAPPER_UNAVAILABLE))
requires_fit = pytest.mark.skipif(
    not CONSTANTS_JSON.is_file(),
    reason=f"{CONSTANTS_JSON.relative_to(REPO_ROOT).as_posix()} is missing; "
           f"run telemetry/fit_tm_constants.py")


def wrapper():
    import playing.uci_wrapper_v6 as module
    return module


# ---------------------------------------------------------------------------
# Part 0 — the engine's constants ARE the fitted constants
# ---------------------------------------------------------------------------


@requires_fit
def test_part0_the_module_constants_match_the_fit_that_produced_them():
    """The one way a hard-coded constants table can rot.

    `time_manager.py` carries the numbers rather than reading the JSON, because
    an engine that needs a file on disk to plan a move has a new way to fail on
    move one. The cost of that choice is exactly this test: if someone refits
    and does not update the module, or edits the module and does not refit, the
    two disagree here rather than in a rated game.
    """
    fit = json.loads(CONSTANTS_JSON.read_text(encoding="utf-8"))
    c = DEFAULT_CONSTANTS

    assert c.a == fit["moves_left"]["A"]
    assert c.tau == fit["moves_left"]["tau"]
    assert c.s == pytest.approx(fit["moves_left"]["s"], abs=1e-4)
    assert c.moves_left_floor == fit["moves_left"]["floor_our_moves"]

    assert c.nps_global == pytest.approx(fit["nps"]["global_median"], abs=1.0)
    assert c.nps_alpha == fit["nps"]["alpha"]
    fitted_buckets = [(b["lo"], b["hi"], float(b["median"]))
                      for b in fit["nps"]["buckets"]]
    assert list(c.nps_buckets) == fitted_buckets

    assert c.theta == fit["complexity"]["theta"]
    assert {str(k): v for k, v in MULTIPLIERS.items()} == \
        fit["complexity"]["multipliers"]


@requires_fit
def test_part0_the_multiplier_set_is_mean_neutral_over_the_measured_frequencies():
    """`ANALYSIS.md` §4a's constraint, as a test rather than as a footnote.

    "If `E[multiplier] != 1` the result is a systematic over- or under-spender
    wearing an adaptive costume." The frequencies are F3's, over the 5,172 Arm B
    moves that reached the 25,000 rung.

    THIS IS WHY `m(1)` IS 0.92 AND NOT THE BRIEF'S 1.0. With the common case
    pinned at 1.0 and every other rung above it, `E[m]` is 1.08 by construction
    and this test cannot pass. Rescaling the hand set by its own mean keeps the
    measured ordering — which is the half the data supports — and moves only the
    level, which was chosen by hand anyway.
    """
    fit = json.loads(CONSTANTS_JSON.read_text(encoding="utf-8"))
    table = fit["complexity"]["table"]
    total = sum(row["moves"] for row in table)
    expected = sum(row["moves"] / total * MULTIPLIERS[row["n_competing"]]
                   for row in table)
    assert expected == pytest.approx(1.0, abs=0.01), (
        f"E[m] = {expected:.4f}. A multiplier set whose mean is not 1.0 spends "
        f"{(expected - 1) * 100:+.1f}% more than the base curve on every move, "
        f"which is a level change dressed as an adaptive one.")


@requires_fit
def test_part0_the_measured_ordering_survives_into_the_shipped_multipliers():
    """The magnitudes are hand-chosen; the ORDERING is not, and it is measured.

    P(argmax at 25k differs from final) is monotone in `n_competing` over 5,172
    moves. A multiplier set that did not respect that ordering would be
    spending more on the positions the data says are easier.
    """
    fit = json.loads(CONSTANTS_JSON.read_text(encoding="utf-8"))
    table = sorted(fit["complexity"]["table"], key=lambda r: r["n_competing"])
    rates = [row["p_changed"] for row in table]
    assert rates == sorted(rates), "the measured table is not monotone any more"
    ms = [MULTIPLIERS[row["n_competing"]] for row in table]
    assert ms == sorted(ms), "the multipliers do not follow the measured order"


def test_part0_the_nps_buckets_partition_every_reachable_piece_count():
    """A position with 3 pieces and one with 32 must both land somewhere.

    The endgame bucket is `<= 10` rather than the brief's `10-7 / <= 6` split,
    which is the occupancy adjustment the brief itself asks for — the `<= 6`
    cell holds 28 of L0's 1,805 searches, under the ~100 bar.
    """
    c = DEFAULT_CONSTANTS
    for pieces in range(2, 33):
        assert c.bucket(pieces) is not None, pieces
    assert c.bucket(None) is None
    los = [lo for lo, _, _ in NPS_BUCKETS]
    his = [hi for _, hi, _ in NPS_BUCKETS]
    assert min(los) == 0 and max(his) == 32, "the buckets leave a gap"


def test_part0_nps_rises_monotonically_as_pieces_come_off():
    """F2's headline, pinned. If a refit inverts it, the bucketing is wrong."""
    medians = [med for _, _, med in NPS_BUCKETS]
    assert medians == sorted(medians), medians
    assert medians[-1] / medians[0] > 1.5, (
        "the endgame regime is the whole reason F2 buckets at all; a spread "
        "under 1.5x would not justify the extra state")


# ---------------------------------------------------------------------------
# Part 1 — the control law
# ---------------------------------------------------------------------------


def test_part1_moves_left_is_the_fitted_exponential_in_our_moves():
    tm = TimeManager()
    c = DEFAULT_CONSTANTS
    ours, floored = tm.moves_left(0)
    assert ours == pytest.approx(c.s * c.a / 2.0, rel=1e-9)
    assert not floored
    # Halved because we move on every other ply, and that is the only
    # conversion between the fit's units and the law's.
    assert ours == pytest.approx(48.1, abs=0.2)


def test_part1_moves_left_never_falls_below_the_floor():
    """MOVES_LEFT.md's inspection paradox, as the guard the brief demands.

    `E[remaining | alive]` bottoms out at ply 86 and RISES; the exponential
    keeps falling. Past that point an unfloored estimator is optimistic exactly
    where the clock is thinnest, which is `4YCsGtQ8`'s mechanism from the other
    direction.
    """
    tm = TimeManager()
    floor = DEFAULT_CONSTANTS.moves_left_floor
    for ply in range(0, 400, 7):
        ours, floored = tm.moves_left(ply)
        assert ours >= floor, ply
        assert floored == (ours == float(floor))
    assert tm.moves_left(400)[0] == float(floor)


def test_part1_moves_left_is_non_increasing_up_to_the_floor():
    tm = TimeManager()
    values = [tm.moves_left(p)[0] for p in range(0, 200)]
    assert all(b <= a + 1e-9 for a, b in zip(values, values[1:]))


def test_part1_the_worked_check_from_the_brief_is_reproduced():
    """`4YCsGtQ8` at our move 60 — ply 120 — with a truth of 25 of our moves.

    The unfloored estimator says about 17 and over-allocates by 1.5x, and the
    over-allocation compounds every move after it. The floor holds it at 23,
    which UNDER-shoots the truth slightly. That asymmetry is the whole design:
    the floor is wrong in the direction that costs search, not the one that
    costs games.
    """
    tm = TimeManager()
    c = DEFAULT_CONSTANTS
    unfloored = c.s * c.a * math.exp(-120 / c.tau) / 2.0
    ours, floored = tm.moves_left(120)
    assert unfloored < 18.0
    assert floored and ours == float(c.moves_left_floor)
    assert ours < 25, "the floored estimator must still under-shoot the truth"
    assert 25 / unfloored > 1.4, "the unfloored one over-allocates by ~1.5x"


def test_part1_base_time_holds_back_the_reserve_and_the_emergency():
    """`(clock - reserve - emergency) / moves_left + increment`, term by term."""
    tm = TimeManager()
    c = DEFAULT_CONSTANTS
    plan = tm.plan(clock_ms=600_000, increment_ms=3_000, ply=0, piece_count=32,
                   current_root_visits=0, n_legal=20)
    expected_ml = c.s * c.a / 2.0
    expected = (600_000 - c.reserve_ms - c.emergency_ms) / expected_ml + 3_000
    assert plan.base_time_ms == pytest.approx(expected, rel=1e-9)
    assert plan.applicable and not plan.clamped_by_clock


def test_part1_the_emergency_is_what_keeps_the_estimator_off_zero():
    """Spending `time_left/moves_left + inc` for `moves_left` moves lands on 0.

    Asserted as the difference the constant makes rather than as its value: with
    the emergency removed the plan is strictly larger, and the gap is the
    emergency amortised over the remaining moves.
    """
    tm = TimeManager()
    no_emergency = TimeManager(TMConstants(emergency_ms=0.0))
    kwargs = dict(clock_ms=60_000, increment_ms=3_000, ply=40, piece_count=20,
                  current_root_visits=0, n_legal=30)
    with_e = tm.plan(**kwargs).base_time_ms
    without_e = no_emergency.plan(**kwargs).base_time_ms
    assert without_e > with_e
    ml = tm.moves_left(40)[0]
    assert without_e - with_e == pytest.approx(
        DEFAULT_CONSTANTS.emergency_ms / ml, rel=1e-9)


def test_part1_the_forty_percent_clamp_binds_on_a_thin_clock():
    """`_allot`'s existing guard, restated so the manager cannot ask for what
    the deadline would refuse.

    At 4,283 ms with a 3,000 ms increment — `4YCsGtQ8` move 85 — the unclamped
    base would be dominated by the increment and exceed 40% of the clock.
    """
    tm = TimeManager()
    plan = tm.plan(clock_ms=4_283, increment_ms=3_000, ply=170, piece_count=10,
                   current_root_visits=0, n_legal=25)
    assert plan.clamped_by_clock
    assert plan.base_time_ms == pytest.approx(
        DEFAULT_CONSTANTS.clock_fraction_cap * 4_283, rel=1e-9)


def test_part1_a_clock_below_the_holdback_still_returns_a_usable_plan():
    """The manager must not return zero, a negative, or an exception here.

    The deadline is what ends this move; the manager's job is to not make it
    worse. One slice is the floor.
    """
    tm = TimeManager()
    plan = tm.plan(clock_ms=500, increment_ms=0, ply=200, piece_count=8,
                   current_root_visits=0, n_legal=12)
    assert plan.applicable
    assert plan.base_time_ms >= 1.0
    assert plan.target_nodes >= 1


def test_part1_no_clock_means_the_manager_has_no_opinion():
    tm = TimeManager()
    plan = tm.plan(clock_ms=None, increment_ms=None, ply=10, piece_count=32,
                   current_root_visits=0, n_legal=20)
    assert not plan.applicable
    assert plan.target_nodes == 0
    # ... but the floor is still set, so shadow mode measures `n_competing` at
    # the same place Arm B measured it.
    assert plan.floor_at == DEFAULT_CONSTANTS.floor_absolute


def test_part1_target_nodes_is_base_time_times_the_bucket_rate():
    tm = TimeManager()
    plan = tm.plan(clock_ms=600_000, increment_ms=3_000, ply=0, piece_count=32,
                   current_root_visits=0, n_legal=20)
    assert plan.bucket == (25, 32)
    assert plan.nps_est == NPS_BUCKETS[0][2]
    assert plan.target_nodes == int(plan.base_time_ms / 1000.0 * plan.nps_est)


def test_part1_the_target_is_absolute_and_never_below_the_root():
    """Matching the core and `_plan`: `budget` is a root-visit TARGET.

    A target under the root's own count is not a smaller amount of work, it is a
    negative amount of it, and `budget - inherited` is what every log line and
    every caller subtracts.
    """
    tm = TimeManager()
    plan = tm.plan(clock_ms=600_000, increment_ms=3_000, ply=0, piece_count=32,
                   current_root_visits=900_000, n_legal=20)
    assert plan.target_total == 900_000
    assert plan.target_nodes < 900_000


def test_part1_a_node_cap_subordinates_the_manager():
    """Row 3 of the switch table, at the level the arithmetic happens.

    `go nodes N` states the GUI's ceiling for the move; the manager may ask for
    less and never for more. That is what makes `go_commands.nodes` the
    rollback path.
    """
    tm = TimeManager()
    kwargs = dict(clock_ms=600_000, increment_ms=3_000, ply=0, piece_count=32,
                  current_root_visits=0, n_legal=20)
    free = tm.plan(**kwargs)
    capped = tm.plan(**kwargs, node_cap=50_000)
    assert free.target_nodes > 50_000, "the premise of this test"
    assert capped.target_nodes == 50_000


# --- the nps smoother ------------------------------------------------------


def test_part1_each_bucket_starts_at_its_own_fitted_median():
    tm = TimeManager()
    for lo, hi, median in NPS_BUCKETS:
        rate, bucket, seeded = tm.nps_for((lo + hi) // 2)
        assert bucket == (lo, hi)
        assert rate == median
        assert seeded


def test_part1_an_unknown_piece_count_falls_back_to_the_global_median():
    tm = TimeManager()
    rate, bucket, seeded = tm.nps_for(None)
    assert bucket is None and seeded
    assert rate == DEFAULT_CONSTANTS.nps_global


def test_part1_the_smoother_moves_by_alpha_and_only_within_its_bucket():
    tm = TimeManager()
    alpha = DEFAULT_CONSTANTS.nps_alpha
    seed = NPS_BUCKETS[0][2]
    tm.observe(30, delivered=200_000, wall_s=5.0)      # 40,000 sims/s
    got, _bucket, seeded = tm.nps_for(30)
    assert not seeded
    assert got == pytest.approx(alpha * 40_000 + (1 - alpha) * seed, rel=1e-9)
    # The other buckets are untouched: the whole point of bucketing is that an
    # endgame observation does not move the opening estimate.
    assert tm.nps_for(20)[0] == NPS_BUCKETS[1][2]


def test_part1_a_degenerate_search_produces_no_observation():
    """L0's own filter, applied at the source rather than downstream.

    A move ended by `stop` at game end, or by the depth-1 mate short-circuit,
    delivers a handful of simulations in a few milliseconds and its "nps" is a
    division by nothing.
    """
    tm = TimeManager()
    assert tm.observe(30, delivered=12, wall_s=0.004) is None
    assert tm.observe(30, delivered=0, wall_s=9.0) is None
    assert tm.nps_for(30)[2] is True, "still the seed"


def test_part1_new_game_clears_the_smoother():
    """`alpha` was measured within games and never across a boundary (L0 §8)."""
    tm = TimeManager()
    tm.observe(30, delivered=200_000, wall_s=5.0)
    assert not tm.nps_for(30)[2]
    tm.new_game()
    assert tm.nps_for(30)[2]
    assert tm.nps_for(30)[0] == NPS_BUCKETS[0][2]


# --- the floor -------------------------------------------------------------


def test_part1_the_floor_is_the_larger_of_the_count_and_the_fraction():
    """`ANALYSIS.md` §3: "express it as a fraction, not a count".

    25,000 is 42% of a 60,000 allocation and 6% of a 400,000 one, and once the
    budget varies only one of those is the floor anyone meant.
    """
    tm = TimeManager()
    c = DEFAULT_CONSTANTS
    assert tm.floor_for(60_000, n_legal=30) == c.floor_absolute
    assert tm.floor_for(800_000, n_legal=30) == int(c.floor_fraction * 800_000)
    assert tm.floor_for(200_000, n_legal=30) == c.floor_absolute, (
        "FLOOR_FRACTION is chosen so the two coincide at the deployed budget")


def test_part1_a_forcing_move_bypasses_the_floor():
    """`n_legal <= 2` is provably safe and free, per the brief.

    With one legal reply the single visited child is trivially unreachable and
    the exit fires at once; with two there is nothing a floor is protecting.
    Recaptures are deliberately NOT in this set — `n_lock` for that subset is
    computable from Arm B and is out of v1.
    """
    tm = TimeManager()
    assert tm.floor_for(200_000, n_legal=1) == 0
    assert tm.floor_for(200_000, n_legal=2) == 0
    assert tm.floor_for(200_000, n_legal=3) == DEFAULT_CONSTANTS.floor_absolute


def _plan_at(target_nodes: int, current: int = 0) -> TMPlan:
    plan = TMPlan()
    plan.applicable = True
    plan.target_nodes = target_nodes
    plan.target_total = max(current, target_nodes)
    plan.floor_at = 25_000
    return plan


def test_part1_at_floor_counts_competitors_at_theta_over_the_top_four():
    """`n_competing = |{c in top4 : visits(c) >= theta * visits(leader)}|`.

    TOP FOUR AND NO MORE, because that is the statistic F3 was fitted on:
    `move_stats` records `top4` and `n_competing` saturates at 4 there. Reading
    a fifth child here would apply a multiplier fitted on a different quantity.
    """
    tm = TimeManager()
    plan = _plan_at(200_000)
    children = [("a", 1000), ("b", 600), ("c", 490), ("d", 100), ("e", 900)]
    tm.at_floor(plan, children, delivered=25_000, current_root_visits=25_000)
    # Sorted first: 1000, 900, 600, 490 are the top four; theta=0.5 keeps
    # 1000, 900 and 600.
    assert plan.n_competing == 3


def test_part1_at_floor_exits_when_one_competitor_is_provably_alone():
    """Branch one of three, and the one Arm B prices at 22.3% of moves.

    The criterion is `ANALYSIS.md`'s: the leader's visit margin already exceeds
    every simulation the target has left, so no redistribution of the remainder
    can change the argmax. Measured over 5,172 laddered moves, the argmax
    changes on 0 of the moves where it fires.
    """
    tm = TimeManager()
    plan = _plan_at(30_000, current=28_000)
    decision = tm.at_floor(plan, [("a", 20_000), ("b", 100)],
                           delivered=25_000, current_root_visits=28_000)
    assert decision.exit_now
    assert decision.n_competing == 1 and decision.leader_unreachable
    assert plan.would_have_exited_at == 25_000


def test_part1_at_floor_does_not_exit_when_the_runner_up_can_still_catch_up():
    tm = TimeManager()
    plan = _plan_at(200_000, current=25_000)
    decision = tm.at_floor(plan, [("a", 13_000), ("b", 11_000)],
                           delivered=25_000, current_root_visits=25_000)
    assert not decision.exit_now
    assert not decision.leader_unreachable


def test_part1_at_floor_grows_the_target_on_a_contested_position():
    tm = TimeManager()
    plan = _plan_at(200_000, current=25_000)
    children = [("a", 8_000), ("b", 7_000), ("c", 6_000), ("d", 4_000)]
    decision = tm.at_floor(plan, children, delivered=25_000,
                           current_root_visits=25_000)
    assert decision.n_competing == 4
    assert decision.multiplier == MULTIPLIERS[4]
    assert decision.new_target_total == int(200_000 * MULTIPLIERS[4])
    assert plan.target_after_multiplier == decision.new_target_total


def test_part1_at_floor_shrinks_the_target_on_an_easy_one():
    """The half of mean-neutrality that shows up as behaviour.

    `m(1) = 0.92`, so an uncontested position that is NOT yet proven spends 8%
    less than the base curve rather than exactly it. That is where the 8% the
    contested positions spend comes from.
    """
    tm = TimeManager()
    plan = _plan_at(200_000, current=25_000)
    decision = tm.at_floor(plan, [("a", 20_000), ("b", 4_000)],
                           delivered=25_000, current_root_visits=25_000)
    assert decision.n_competing == 1 and not decision.exit_now
    assert decision.multiplier == MULTIPLIERS[1] < 1.0
    assert decision.new_target_total == int(200_000 * MULTIPLIERS[1])


def test_part1_at_floor_never_targets_below_the_root_it_is_standing_on():
    tm = TimeManager()
    plan = _plan_at(50_000, current=400_000)
    decision = tm.at_floor(plan, [("a", 300_000), ("b", 90_000)],
                           delivered=25_000, current_root_visits=400_000)
    assert decision.new_target_total >= 400_000


def test_part1_at_floor_survives_a_root_with_no_visited_children():
    tm = TimeManager()
    plan = _plan_at(200_000)
    decision = tm.at_floor(plan, [], delivered=25_000, current_root_visits=0)
    assert not decision.exit_now and decision.n_competing == 0


def test_part1_the_record_carries_every_field_the_brief_names():
    """Part 3's eight, by name. A renamed field is a shadow analysis that
    silently measures nothing."""
    plan = _plan_at(200_000)
    record = plan.record()
    for key in ("tm_moves_left", "tm_base_time_ms", "tm_nps_est",
                "tm_target_nodes", "tm_n_competing", "tm_multiplier",
                "tm_target_after_multiplier", "tm_would_have_exited_at"):
        assert key in record, key


# ---------------------------------------------------------------------------
# Part 2 — the switches
# ---------------------------------------------------------------------------


@requires_wrapper
def test_part2_time_manager_is_a_check_option_defaulting_to_false():
    """The one permitted difference in the `uci` handshake.

    Unlike `--move-stats`, where R3 kept the channel off the UCI surface because
    zero observable difference was required, a time manager is a capability and
    a capability declaration is what an option line is.
    """
    from playing.v6.playv6 import EngineConfig
    module = wrapper()
    option = next(o for o in module.OPTIONS if o.name == "TimeManager")
    assert option.kind == "check"
    assert option.attr == "time_manager"
    assert EngineConfig().time_manager is False
    assert not module.missing_options(), (
        "adding an EngineConfig field without its option is the invisible-"
        "configuration defect C11 closes")


@requires_wrapper
def test_part2_the_handshake_gains_exactly_one_line():
    """Counted rather than eyeballed: one new `option name`, nothing else.

    The count is derived from the option table, which is the thing the `uci`
    response is generated from, so this fails if a second option is smuggled in
    alongside the manager.
    """
    module = wrapper()
    names = [o.name for o in module.OPTIONS]
    assert names.count("TimeManager") == 1
    assert len(names) == len(set(names))


def _uci_for_plan(config, root_visits: int = 0, move_stats=None,
                  children=()):
    """A UCIEngine with just enough of itself to answer a planner question.

    `__new__` rather than `__init__`: constructing the real thing builds an
    `Engine`, which imports torch and loads a model. Every attribute the
    planner touches is set here and nothing else is, so a planner that started
    reaching for the evaluator would fail loudly rather than quietly.
    """
    import chess
    module = wrapper()
    uci = module.UCIEngine.__new__(module.UCIEngine)
    uci.config = config
    search = type("_S", (), {"root_visits": root_visits,
                             "root_children": staticmethod(lambda: list(children))})()
    uci.engine = type("_E", (), {"ready": True, "search": search})()
    uci.board = chess.Board()
    uci.move_stats = move_stats
    uci.tm = TimeManager()
    return uci, module


@requires_wrapper
def test_part2_row1_off_plus_nodes_is_byte_identical_to_no_manager_at_all():
    """The identity case, asserted by calling the planner both ways.

    Not "it looks the same as it used to" — the same call with the manager's
    plan present and with it absent must return the same tuple, on a config
    where the switch is off. That is the property ground rule 1 asks for and it
    is checkable without a second build.
    """
    from playing.v6.playv6 import EngineConfig
    uci, module = _uci_for_plan(EngineConfig(time_manager=False,
                                             sim_cap=200_000))
    params = module.GoParams(["nodes", "200000"])
    plan = uci._tm_make_plan(params)          # None: nothing would read it
    assert plan is None

    now = time.monotonic()
    with_tm = uci._plan(params, since=now, tm=plan)
    without = uci._plan(params, since=now, tm=None)
    assert with_tm == without
    assert with_tm[0] == 200_000 and with_tm[3] == "nodes"


@requires_wrapper
def test_part2_row2_off_plus_a_clock_takes_the_existing_time_path():
    from playing.v6.playv6 import EngineConfig
    uci, module = _uci_for_plan(EngineConfig(time_manager=False))
    params = module.GoParams(["wtime", "300000", "btime", "300000",
                              "winc", "3000", "binc", "3000"])
    budget, deadline, nominal, source, _note = uci._plan(params)
    assert source == "time"
    assert nominal is None
    assert deadline is not None
    assert budget == uci.config.sim_cap


@requires_wrapper
def test_part2_row3_on_plus_nodes_honours_n_as_an_absolute_cap():
    """The rollback path, and it must be reachable by editing `config.yml`.

    With `go_commands.nodes: 200000` in place the manager cannot exceed today's
    budget no matter what it computes — and the offline replay measures it
    wanting to on 92% of moves, so this is not a theoretical guard.
    """
    from playing.v6.playv6 import EngineConfig
    uci, module = _uci_for_plan(EngineConfig(time_manager=True))
    params = module.GoParams(["wtime", "600000", "btime", "600000",
                              "winc", "3000", "binc", "3000",
                              "nodes", "200000"])
    plan = uci._tm_make_plan(params)
    assert plan is not None and plan.applicable
    budget, deadline, nominal, source, _note = uci._plan(params, tm=plan)
    assert budget <= 200_000, "the GUI's N is a cap the manager may not exceed"
    assert deadline is not None, "the deadline is armed on this path too"
    assert source == "manager"


@requires_wrapper
def test_part2_row4_on_plus_a_clock_gives_the_manager_the_budget():
    from playing.v6.playv6 import EngineConfig
    config = EngineConfig(time_manager=True, sim_cap=1_000_000)
    uci, module = _uci_for_plan(config)
    params = module.GoParams(["wtime", "600000", "btime", "600000",
                              "winc", "3000", "binc", "3000"])
    plan = uci._tm_make_plan(params)
    budget, deadline, nominal, source, _note = uci._plan(params, tm=plan)
    assert source == "manager"
    assert budget == plan.target_nodes
    assert nominal == budget, "a node target IS a request, unlike a ceiling"
    assert deadline is not None


# ---------------------------------------------------------------------------
# The movestogo handoff -- _allot and the manager dividing by the same number
# ---------------------------------------------------------------------------
#
# MEASURED IN DEPLOYMENT, NOT HYPOTHESISED: `_allot` used a hard-coded
# `movestogo` of 30 while the manager divided by its own fitted `moves_left`
# (about 26 in the middlegame, floored at 23 late). The two allocators dividing
# the same clock by two different numbers is not a safety defect -- the
# deadline was always a valid upper bound -- but it is why the first live run
# (`CLOCK_AND_PONDER.md` section 8) measured `reason=time` on 35% of
# middlegame moves and 65% late: `_allot`'s more conservative divisor kept
# truncating a target the manager believed it could afford. `_tm_movestogo`
# closes that gap by handing `_allot` the SAME `plan.moves_left` the manager's
# own `base_time` divided by.


@requires_wrapper
def test_part1_tm_movestogo_is_none_when_the_manager_is_off():
    from playing.v6.playv6 import EngineConfig
    uci, module = _uci_for_plan(EngineConfig(time_manager=False))
    params = module.GoParams(["wtime", "600000", "btime", "600000"])
    plan = uci._tm_make_plan(params)          # None: nothing would read it
    assert uci._tm_movestogo(plan) is None


@requires_wrapper
def test_part1_tm_movestogo_is_none_when_the_manager_has_no_clock_to_divide():
    """`plan.applicable` is False on a fixed-node benchmark; there is no
    `moves_left` to hand `_allot` because there was nothing to divide."""
    from playing.v6.playv6 import EngineConfig
    uci, module = _uci_for_plan(EngineConfig(time_manager=True))
    params = module.GoParams(["nodes", "50000"])
    plan = uci._tm_make_plan(params)
    assert plan is not None and not plan.applicable
    assert uci._tm_movestogo(plan) is None


@requires_wrapper
def test_part1_tm_movestogo_returns_the_plans_own_moves_left_unrounded():
    """THE SAME FLOAT the manager's `base_time` divided by, not a rounded
    approximation of it -- "the same number", literally."""
    from playing.v6.playv6 import EngineConfig
    uci, module = _uci_for_plan(EngineConfig(time_manager=True))
    params = module.GoParams(["wtime", "600000", "btime", "600000",
                              "winc", "3000", "binc", "3000"])
    plan = uci._tm_make_plan(params)
    mo = uci._tm_movestogo(plan)
    assert mo == plan.moves_left
    assert mo != int(mo), "the premise: a fresh-root moves_left is not an integer"


@requires_wrapper
def test_part1_the_floor_survives_the_handoff_into_allot():
    """THE GUARDRAIL, AS A TEST. `_tm_movestogo` must return the FLOORED
    `moves_left` -- `TimeManager.moves_left`'s `max(FLOOR, fitted)` -- not the
    raw estimator output. This is the whole reason `2mLvILE3` (193 of our
    moves, ply 385) didn't flag: at that ply the unfloored curve says ~1.6
    moves remain, which would have made `_allot` divide by 1.6 and hand back
    most of a 23-second clock in one move.
    """
    from playing.v6.playv6 import EngineConfig
    uci, module = _uci_for_plan(EngineConfig(time_manager=True))
    params = module.GoParams(["wtime", "23000", "btime", "23000", "winc", "3000"])
    # `tm.plan` takes `ply` directly -- no need to walk a real board through
    # 400 plies (and a deterministic "always the first legal move" walk hits
    # an automatic draw by repetition long before it gets there anyway).
    plan = uci.tm.plan(clock_ms=23_000.0, increment_ms=3_000, ply=400,
                       piece_count=8, current_root_visits=0, n_legal=20)
    assert plan.moves_left_floored, "the premise: this ply must floor"
    assert plan.moves_left == float(DEFAULT_CONSTANTS.moves_left_floor)
    mo = uci._tm_movestogo(plan)
    assert mo == float(DEFAULT_CONSTANTS.moves_left_floor)
    # And `_allot` with it does not collapse to a near-zero divisor: dividing a
    # 23 s clock by 23 rather than by 1.6 is the whole point.
    allotted = uci._allot(params, movestogo_override=mo)
    naive = uci._allot(params, movestogo_override=1.6)
    assert allotted < naive, "flooring must ask for LESS than the raw estimate"


@requires_wrapper
def test_part1_allot_divides_by_the_override_instead_of_thirty():
    from playing.v6.playv6 import EngineConfig
    uci, module = _uci_for_plan(EngineConfig())
    params = module.GoParams(["wtime", "600000", "btime", "600000",
                              "winc", "3000"])
    default = uci._allot(params)                       # falls back to 30
    overridden = uci._allot(params, movestogo_override=15.0)
    assert overridden != default
    overhead = EngineConfig().move_overhead_ms / 1000.0
    expected = min(600.0 / 15.0 + 0.8 * 3.0, 0.4 * 600.0) - overhead
    assert overridden == pytest.approx(expected, rel=1e-9)


@requires_wrapper
def test_part1_a_gui_stated_movestogo_still_wins_over_the_override():
    """Real protocol truth about a stage-based time control beats a guess,
    however good the guess. `_tm_movestogo` returns a guess."""
    from playing.v6.playv6 import EngineConfig
    uci, module = _uci_for_plan(EngineConfig())
    params = module.GoParams(["wtime", "600000", "btime", "600000",
                              "winc", "3000", "movestogo", "40"])
    with_override = uci._allot(params, movestogo_override=15.0)
    without = uci._allot(params)
    assert with_override == without, "movestogo=40 from the GUI must win either way"


@requires_wrapper
def test_part1_the_forty_percent_guard_still_binds_a_pathological_override():
    """The guard does not trust the caller. A caller that handed `_allot` a
    movestogo of 1 must still not exceed 40% of the clock."""
    from playing.v6.playv6 import EngineConfig
    uci, module = _uci_for_plan(EngineConfig())
    params = module.GoParams(["wtime", "600000", "btime", "600000"])
    allotted = uci._allot(params, movestogo_override=1.0)
    overhead = EngineConfig().move_overhead_ms / 1000.0
    assert allotted == pytest.approx(0.4 * 600.0 - overhead, rel=1e-9)


@requires_wrapper
def test_part2_the_deadline_now_divides_by_the_managers_moves_left():
    """END TO END, through `_plan`: with the manager on, the armed deadline's
    allotment matches `_allot(movestogo_override=plan.moves_left)` exactly, not
    the pre-existing 30-divided one."""
    from playing.v6.playv6 import EngineConfig
    config = EngineConfig(time_manager=True, sim_cap=1_000_000)
    uci, module = _uci_for_plan(config)
    params = module.GoParams(["wtime", "600000", "btime", "600000",
                              "winc", "3000", "binc", "3000"])
    plan = uci._tm_make_plan(params)
    now = time.monotonic()
    budget, deadline, _n, _s, _note = uci._plan(params, since=now, tm=plan)
    assert deadline is not None
    expected = uci._allot(params, movestogo_override=plan.moves_left)
    assert deadline - now == pytest.approx(expected, abs=1e-6)
    thirty_divided = uci._allot(params)
    assert (deadline - now) != pytest.approx(thirty_divided, abs=1e-3), (
        "the premise: the manager's moves_left must differ from 30 here")


@requires_wrapper
def test_part2_the_deadline_still_uses_thirty_when_the_manager_is_off():
    """THE NON-MANAGER PATH IS UNTOUCHED. `TimeManager: false` must reproduce
    the pre-existing deadline exactly -- this is the regression the whole
    change promises not to cause."""
    from playing.v6.playv6 import EngineConfig
    uci, module = _uci_for_plan(EngineConfig(time_manager=False))
    params = module.GoParams(["wtime", "600000", "btime", "600000",
                              "winc", "3000", "binc", "3000"])
    plan = uci._tm_make_plan(params)              # None: nothing would read it
    now = time.monotonic()
    budget, deadline, _n, _s, _note = uci._plan(params, since=now, tm=plan)
    expected = uci._allot(params)                  # falls back to 30, unchanged
    assert deadline - now == pytest.approx(expected, abs=1e-6)


@requires_wrapper
def test_part2_ponderhit_with_nodes_uses_the_managers_moves_left_too():
    """The nodes-branch of `_plan_after_ponderhit`, which is the branch
    deployment actually takes (`go_commands.nodes` was set when this branch was
    written; it is unset now, but a GUI that DOES send `nodes` on the ponder
    line still gets an aligned deadline)."""
    from playing.v6.playv6 import EngineConfig
    config = EngineConfig(time_manager=True, sim_cap=1_000_000,
                          ponder_max_sims=1_000_000)
    uci, module = _uci_for_plan(config, root_visits=300_000)
    params = module.GoParams(["wtime", "600000", "btime", "600000",
                              "winc", "3000", "binc", "3000", "nodes", "200000"])
    plan = uci._tm_make_plan(params)
    now = time.monotonic()
    _b, deadline, _n, source, _note = uci._plan_after_ponderhit(
        params, since=now, tm=plan)
    assert source == "ponderhit" and deadline is not None
    expected = uci._allot(params, movestogo_override=plan.moves_left)
    assert deadline - now == pytest.approx(expected, abs=1e-6)


@requires_wrapper
def test_part2_ponderhit_with_no_nodes_uses_the_managers_moves_left():
    """The no-`nodes` ponderhit branch: pure clock, and now the same divisor
    as the manager used to size its own (unused, on this branch) target."""
    from playing.v6.playv6 import EngineConfig
    config = EngineConfig(time_manager=True, sim_cap=1_000_000)
    uci, module = _uci_for_plan(config, root_visits=50_000)
    params = module.GoParams(["wtime", "600000", "btime", "600000",
                              "winc", "3000", "binc", "3000"])
    plan = uci._tm_make_plan(params)
    now = time.monotonic()
    _b, deadline, _n, source, _note = uci._plan_after_ponderhit(
        params, since=now, tm=plan)
    assert source == "ponderhit" and deadline is not None
    expected = uci._allot(params, movestogo_override=plan.moves_left)
    assert deadline - now == pytest.approx(expected, abs=1e-6)


@requires_wrapper
def test_part2_ponderhit_deadline_unaffected_when_the_manager_is_off():
    from playing.v6.playv6 import EngineConfig
    config = EngineConfig(time_manager=False)
    uci, module = _uci_for_plan(config, root_visits=50_000)
    params = module.GoParams(["wtime", "600000", "btime", "600000",
                              "winc", "3000", "binc", "3000"])
    plan = uci._tm_make_plan(params)               # None
    now = time.monotonic()
    _b, deadline, _n, _s, _note = uci._plan_after_ponderhit(
        params, since=now, tm=plan)
    expected = uci._allot(params)                   # falls back to 30, unchanged
    assert deadline - now == pytest.approx(expected, abs=1e-6)


@requires_wrapper
def test_part2_the_manager_never_touches_a_ponder():
    """A ponder is not a move; it is speculative work on the opponent's clock.

    The quantity that bounds it is `ponder_max_sims_resolved`, and C11c's named
    failure is "pondering silently does nothing" — which is exactly what an
    absolute target from a time manager would cause on a reused tree.
    """
    from playing.v6.playv6 import EngineConfig
    uci, module = _uci_for_plan(EngineConfig(time_manager=True),
                                root_visits=100_000)
    params = module.GoParams(["ponder", "wtime", "600000", "btime", "600000",
                              "nodes", "200000"])
    plan = uci._tm_make_plan(params)
    budget, deadline, _n, source, _note = uci._plan(params, tm=plan)
    assert source == "ponder"
    assert deadline is None
    assert budget > 100_000, "the ponder still extends beyond what is resident"


@requires_wrapper
def test_part2_the_ponderhit_path_keeps_ponderhit_floor_semantics():
    """The manager supplies `N`. What a HIT must deliver is `PonderhitFloor`'s
    decision, which is a separate operator choice already deployed at 0.4.

    A manager that imposed its own absolute target here would silently override
    it, and the brief's rule is that the switches stay independent.
    """
    from playing.v6.playv6 import EngineConfig
    config = EngineConfig(time_manager=True, ponderhit_floor=0.4,
                          sim_cap=1_000_000)
    uci, module = _uci_for_plan(config, root_visits=300_000)
    params = module.GoParams(["wtime", "600000", "btime", "600000",
                              "winc", "3000", "binc", "3000",
                              "nodes", "200000"])
    plan = uci._tm_make_plan(params)
    budget, deadline, nominal, source, _note = uci._plan_after_ponderhit(
        params, tm=plan)
    n = min(200_000, plan.target_nodes)
    assert nominal == n
    assert budget == max(n, 300_000 + int(0.4 * n))
    assert source == "ponderhit"
    assert deadline is not None


@requires_wrapper
def test_part2_a_fixed_budget_arm_does_not_acquire_a_time_manager():
    """`FixedSims` means "the clock is deliberately not consulted".

    A benchmark that compares engines on simulation count must not have one of
    them quietly re-budgeting from a clock, and the fixed branch is tested first
    in the planner precisely so nothing downstream can.
    """
    from playing.v6.playv6 import EngineConfig
    uci, module = _uci_for_plan(EngineConfig(time_manager=True,
                                             fixed_sims=4_000))
    params = module.GoParams(["wtime", "600000", "btime", "600000"])
    budget, deadline, nominal, source, _note = uci._plan(
        params, tm=uci._tm_make_plan(params))
    assert source == "fixed" and budget == 4_000 and deadline is None


# ---------------------------------------------------------------------------
# Part 3 — shadow mode
# ---------------------------------------------------------------------------


class _Collector:
    enabled = True


@requires_wrapper
def test_part3_nothing_is_computed_when_nothing_would_read_it():
    """"Off means byte-identical" is a property of the control flow here.

    With the manager off and no `--move-stats` channel — a bare pipe, a
    benchmark, every existing test — the plan is never built, so the manager
    contributes not one line of executed code to a move.
    """
    from playing.v6.playv6 import EngineConfig
    uci, module = _uci_for_plan(EngineConfig(time_manager=False))
    assert uci._tm_shadow is False
    assert uci._tm_make_plan(module.GoParams(["wtime", "60000"])) is None
    assert uci._tm_budget_hook(None, 200_000) is None


@requires_wrapper
def test_part3_move_stats_alone_turns_the_shadow_on():
    from playing.v6.playv6 import EngineConfig
    uci, module = _uci_for_plan(EngineConfig(time_manager=False),
                                move_stats=_Collector())
    assert uci._tm_shadow is True
    plan = uci._tm_make_plan(module.GoParams(["wtime", "600000", "btime",
                                              "600000", "winc", "3000"]))
    assert plan is not None and plan.applicable and plan.target_nodes > 0


@requires_wrapper
def test_part3_the_shadow_hook_evaluates_and_then_declines_to_act():
    """The whole of Part 3 in one assertion.

    The hook reads the root, fills `tm_n_competing` and the rest, and returns
    None — so the search runs to the budget the engine chose and the record
    carries what the manager would have done. A hook that returned a number
    here would be the manager acting with its switch off.
    """
    from playing.v6.playv6 import EngineConfig
    children = [("a", 20_000), ("b", 300)]
    uci, module = _uci_for_plan(EngineConfig(time_manager=False),
                                root_visits=25_000, move_stats=_Collector(),
                                children=children)
    params = module.GoParams(["wtime", "600000", "btime", "600000",
                              "winc", "3000", "nodes", "200000"])
    plan = uci._tm_make_plan(params)
    hook = uci._tm_budget_hook(plan, 200_000)
    assert hook is not None
    assert hook(1_000, 1_000) is None, "below the floor, nothing happens"
    assert plan.n_competing is None
    assert hook(plan.floor_at, 25_000) is None, "at the floor, but shadow"
    assert plan.floor_evaluated and plan.n_competing == 1
    assert plan.multiplier == MULTIPLIERS[1]


@requires_wrapper
def test_part3_the_live_hook_acts_and_fires_exactly_once():
    """One evaluation per move, by construction rather than by convention.

    The rule is priced on a single reading of the root; evaluating it every
    slice would apply the multiplier repeatedly and turn a 1.39x into whatever
    the slice count happened to be.
    """
    from playing.v6.playv6 import EngineConfig
    children = [("a", 9_000), ("b", 8_000), ("c", 7_000), ("d", 6_000)]
    config = EngineConfig(time_manager=True, sim_cap=1_000_000)
    uci, module = _uci_for_plan(config, root_visits=30_000, children=children)
    params = module.GoParams(["wtime", "600000", "btime", "600000",
                              "winc", "3000"])
    plan = uci._tm_make_plan(params)
    hook = uci._tm_budget_hook(plan, plan.target_total)
    first = hook(plan.floor_at, 30_000)
    assert first == int(plan.target_nodes * MULTIPLIERS[4])
    assert hook(plan.floor_at + 50_000, 80_000) is None, "fired already"


@requires_wrapper
def test_part3_the_multiplier_may_not_walk_past_simcap_or_the_tree_ceiling():
    """The guard that keeps TM Part 1 from undoing TC Part 4b.

    `_plan` clamps its node budget at `SimCap`. A 1.39x applied afterwards to
    the UNCLAMPED target walks straight past it, and past `TreeMaxVisits` with
    it — and Part 4b's whole content is that the resident tree is bounded. The
    manager is allowed to be wrong about the budget; it is not allowed to
    re-open a defect that was closed.
    """
    from playing.v6.playv6 import EngineConfig
    config = EngineConfig(time_manager=True, sim_cap=200_000,
                          ponder_max_sims=200_000)
    children = [("a", 9_000), ("b", 8_000), ("c", 7_000), ("d", 6_000)]
    uci, module = _uci_for_plan(config, root_visits=30_000, children=children)
    params = module.GoParams(["wtime", "600000", "btime", "600000",
                              "winc", "3000"])
    plan = uci._tm_make_plan(params)
    budget, _d, _n, _s, _note = uci._plan(params, tm=plan)
    assert plan.target_nodes > config.sim_cap, "the premise: the manager wants more"

    hook = uci._tm_budget_hook(plan, budget)
    revised = hook(plan.floor_at, 30_000)
    assert revised <= 30_000 + config.sim_cap
    assert revised <= config.tree_ceiling
    assert revised >= budget, "the planner's own allowance still stands"


@requires_wrapper
def test_part3_the_live_hook_ends_a_decided_move_by_lowering_the_budget():
    """The exit, expressed as a budget and not as a second `break`.

    There is exactly one place in the slice loop where a search can end on
    nodes, and this keeps it that way — `reason` comes out `budget`, which is
    the truth: the budget is what the move ended on.
    """
    from playing.v6.playv6 import EngineConfig
    config = EngineConfig(time_manager=True, sim_cap=1_000_000)
    uci, module = _uci_for_plan(config, root_visits=30_000,
                                children=[("a", 29_000), ("b", 200)])
    params = module.GoParams(["wtime", "600000", "btime", "600000",
                              "winc", "3000"])
    plan = uci._tm_make_plan(params)
    hook = uci._tm_budget_hook(plan, plan.target_total)
    # A root already holding 900,000 visits against a target below it: the
    # leader is unreachable and there is one competitor.
    revised = hook(plan.floor_at, 900_000)
    assert revised == 900_000, "the exit is the root's own visit count"
    assert plan.would_have_exited_at == plan.floor_at


@requires_wrapper
def test_part3_a_failing_root_read_does_not_end_a_rated_game():
    """Same contract as `_ms_record`: telemetry that can lose a game is worse
    than no telemetry."""
    from playing.v6.playv6 import EngineConfig
    config = EngineConfig(time_manager=True, sim_cap=1_000_000)
    uci, module = _uci_for_plan(config, root_visits=30_000)

    def boom():
        raise RuntimeError("arena went away")

    uci.engine.search.root_children = boom
    params = module.GoParams(["wtime", "600000", "btime", "600000"])
    plan = uci._tm_make_plan(params)
    hook = uci._tm_budget_hook(plan, plan.target_total)
    assert hook(plan.floor_at, 30_000) is None


# ---------------------------------------------------------------------------
# The slice loop's contract, which is what makes "off" free
# ---------------------------------------------------------------------------


def test_search_move_takes_a_budget_hook_that_defaults_to_none():
    """The identity guarantee, at the signature.

    One `is not None` test per slice — the same test `on_slice` and
    `should_stop` already carry — and the loop is otherwise the loop it was.
    """
    import inspect
    from playing.v6.playv6 import Engine
    sig = inspect.signature(Engine.search_move)
    assert "budget_hook" in sig.parameters
    assert sig.parameters["budget_hook"].default is None
    source = inspect.getsource(Engine.search_move)
    assert "if budget_hook is not None:" in source
    assert "revised = budget_hook(" in source
