#!/usr/bin/env python3
"""C8 measurements — arena high-water over whole games, and what a compaction costs.

Two questions, and the acceptance criterion only asks the first:

1.  **Does game-long tree reuse stay inside the 2-3M node budget?** (criterion 3.)
    Measured over the corpus's 80-ply game, from the engine's own high-water
    counter — the peak of EITHER arena, because during a compaction the source
    subtree and its copy are alive at the same instant.

2.  **What does the ping-pong actually cost?** Scope §2.3 estimates "a few ms"
    for a ~600k-node copy and treats that as affordable against a ~1 s move.
    That is an estimate in a design document; this turns it into a number, split
    into the copy and the structural diff, because the diff is optional in a
    Release build and a reader deciding whether to enable it should know what
    they are buying.

THE EXTRAPOLATION IS LABELLED AS ONE
====================================
The corpus was generated by the Python reference, and at 15,000 simulations per
move for 80 plies that would have taken most of a day rather than 25 minutes. So
the 80-ply game runs at 2,000 and the peak is reported at 2,000, beside the
measured nodes-per-simulation rate and the figure that rate implies at 15,000.
The implied figure is not a measurement and is not asserted anywhere; scope
§2.3's own budget was derived the same way (~40 nodes/sim x 15k sims).

Usage:
    python tools/bench_c8.py
    python tools/bench_c8.py --json out.json
"""

import argparse
import json
import statistics
import sys
import time
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import guofish_core  # noqa: E402

GOLDEN = REPO_ROOT / "golden"
ARENA_CAPACITY = 1 << 19
CACHE_SLOTS = 1 << 20

# Scope §2.3's production budget, for the extrapolation only.
PRODUCTION_SIMS = 15_000
NODE_BUDGET_LOW = 2_000_000
NODE_BUDGET_HIGH = 3_000_000


def load():
    manifest = json.loads((GOLDEN / "c8_reuse_manifest.json").read_text(encoding="utf-8"))
    with np.load(GOLDEN / "c8_reuse_dump.npz") as data:
        dump = {k: data[k] for k in data.files}
    return manifest, dump


def play(game, dump, *, verify):
    config = guofish_core.SearchConfig(
        virtual_loss=game["virtual_loss"], max_tree_depth=game["max_tree_depth"],
        arena_capacity=ARENA_CAPACITY, cache_slots=CACHE_SLOTS,
        verify_compaction=verify)
    search = guofish_core.ReplaySearchDouble(config)
    search.load_dump(dump["keys"], dump["is_root"], dump["move_offset"],
                     dump["moves"], dump["priors"], dump["values"])
    search.set_position(game["root_fen"], game["history"])

    apply_ms = []
    sizes = []
    delivered = 0
    for audit in game["snapshots"]:
        if audit["kind"] == "search":
            before = search.root_visits
            search.search(game["sims"])
            delivered += search.root_visits - before
            sizes.append(int(search.nodes))
            continue
        started = time.perf_counter()
        search.apply_move(audit["move"])
        apply_ms.append((time.perf_counter() - started) * 1000.0)
    return search, apply_ms, sizes, delivered


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", type=Path, default=None)
    args = parser.parse_args()

    manifest, dump = load()
    info = guofish_core.build_info()
    print(f"build: {info['compiler']}, asan={info['asan']}, asserts={info['asserts']}, "
          f"DEBUG_VL={guofish_core.DEBUG_VL}")
    print(f"arena capacity {ARENA_CAPACITY} nodes per arena, ping-pong pair\n")

    rows = []
    header = (f"{'game':<16}{'plies':>6}{'sims':>6}{'peak':>9}{'nodes/sim':>10}"
              f"{'kept%':>7}{'reuse x':>9}{'apply p50':>11}{'max':>8}"
              f"{'  (no diff) p50':>16}{'max':>8}")
    print(header)
    print("-" * len(header))

    for game in manifest["games"]:
        search, apply_ms, sizes, delivered = play(game, dump, verify=True)
        # The same game with the structural diff off, so its cost is a
        # difference rather than an estimate. Two runs of the same deterministic
        # replay: the trees are identical, only the checking differs.
        _, plain_ms, _, _ = play(game, dump, verify=False)

        reuse = search.reuse_stats()
        keep = (100.0 * reuse["nodes_copied"] /
                max(1, reuse["nodes_copied"] + reuse["nodes_dropped"]))
        plies = len(game["played"])
        # PEAK NODES PER SIMULATION OF MOVE BUDGET, which is the rate scope §2.3
        # sizes the arena from ("~40 nodes/sim, 15K sims -> ~600k nodes/search").
        # The divisor is the TARGET, not the sims actually delivered: with reuse
        # most of a move's budget is already in the tree, and dividing by the
        # ~600 new simulations would report a rate three times too high for a
        # tree the same size.
        per_sim = reuse["arena_high_water"] / game["sims"]
        row = {
            "game": game["name"],
            "plies": plies,
            "sims": game["sims"],
            "peak_nodes": reuse["arena_high_water"],
            "largest_tree": max(sizes) if sizes else 0,
            "nodes_per_sim": round(per_sim, 1),
            "nodes_copied": reuse["nodes_copied"],
            "nodes_dropped": reuse["nodes_dropped"],
            "keep_percent": round(keep, 1),
            "largest_copy": reuse["largest_copy"],
            "delivered_sims": delivered,
            # Scope §3's "tree-reuse factor": budget over sims actually run.
            "reuse_factor": round(game["sims"] / max(1.0, delivered / plies), 2),
            "apply_ms_p50": round(statistics.median(apply_ms), 3),
            "apply_ms_max": round(max(apply_ms), 3),
            "apply_ms_p50_no_diff": round(statistics.median(plain_ms), 3),
            "apply_ms_max_no_diff": round(max(plain_ms), 3),
            "bytes_reserved": reuse["arena_bytes_reserved"],
        }
        rows.append(row)
        print(f"{row['game']:<16}{row['plies']:>6}{row['sims']:>6}{row['peak_nodes']:>9}"
              f"{row['nodes_per_sim']:>10.1f}{row['keep_percent']:>7.1f}"
              f"{row['reuse_factor']:>9.2f}{row['apply_ms_p50']:>11.3f}"
              f"{row['apply_ms_max']:>8.3f}{row['apply_ms_p50_no_diff']:>16.3f}"
              f"{row['apply_ms_max_no_diff']:>8.3f}")

    biggest = max(rows, key=lambda r: r["largest_copy"])
    print(f"\nstructural diff (scope §7), on the largest trees ({biggest['game']}, "
          f"{biggest['largest_copy']} nodes copied at the peak): apply p50 "
          f"{biggest['apply_ms_p50']:.3f} ms with it, "
          f"{biggest['apply_ms_p50_no_diff']:.3f} ms without — "
          f"{biggest['apply_ms_p50'] - biggest['apply_ms_p50_no_diff']:+.3f} ms")

    # Criterion 3, and the extrapolation, kept visibly apart.
    verified = next(r for r in rows if r["game"] == "quiet-80")
    peak = verified["peak_nodes"]
    print(f"\nMEASURED  quiet-80: {verified['plies']} plies at {verified['sims']} sims/move, "
          f"{verified['delivered_sims']} delivered simulations "
          f"(reuse factor {verified['reuse_factor']:.2f}x)")
    print(f"          arena high-water {peak} nodes "
          f"({100.0 * peak / NODE_BUDGET_LOW:.1f}% of the {NODE_BUDGET_LOW:,} budget floor), "
          f"{verified['bytes_reserved'] / (1 << 20):.1f} MiB reserved for the pair "
          f"at capacity {ARENA_CAPACITY:,}")
    print(f"          {verified['nodes_per_sim']:.1f} peak nodes per simulation of move budget")

    rate = max(r["nodes_per_sim"] for r in rows)
    implied = rate * PRODUCTION_SIMS
    print(f"DERIVED   the worst rate in the corpus is {rate:.1f} nodes/sim "
          f"({max(rows, key=lambda r: r['nodes_per_sim'])['game']}); at "
          f"{PRODUCTION_SIMS:,} sims/move that implies ~{implied:,.0f} peak nodes, inside "
          f"the {NODE_BUDGET_LOW:,}-{NODE_BUDGET_HIGH:,} budget.")
    print(f"          NOT A MEASUREMENT. The reference corpus this replays was generated "
          f"at 2,000-5,000 sims; scope §2.3's own budget was derived the same way "
          f"(~40 nodes/sim x 15k sims).")

    if args.json:
        args.json.write_text(json.dumps(
            {"build": info, "debug_vl": guofish_core.DEBUG_VL,
             "arena_capacity": ARENA_CAPACITY, "games": rows,
             "worst_nodes_per_sim": rate,
             "implied_peak_at_production": round(implied)}, indent=2) + "\n",
            encoding="utf-8")
        print(f"\nwrote {args.json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
