"""Populate the C2 table in BENCH.md — tokenization throughput.

NOTE: this is a benchmark, not a golden-data generator. Nothing here writes to
golden/ and nothing here is a reference implementation (Global Rule 2). It reads
the FEN column of golden/tokens.npz purely as a source of realistic input.

Usage:
    python tools/bench_c2.py [--repeats N] [--limit N] [--python]

Three numbers, and they are not interchangeable:

  encoder        `guofish_core.tokenize_bench` — the FENs are copied into C++
                 strings first and the timed region touches no Python object,
                 so this is the cost of the encoder alone. It is the figure the
                 100x acceptance criterion is judged against, because it is the
                 one the C++ search will actually pay: by C5 the FENs will not
                 be Python objects at all.

  fill()         `TokenBatch.fill(fens)` end to end, including materialising the
                 iterable and borrowing each str's UTF-8 buffer. This is what a
                 caller still driving the search from Python sees, and it is
                 slower for reasons that have nothing to do with tokenizing.

  python         The reference, `core.mctsv4.board_to_tokens`, on the same FENs.
                 Off by default: it imports torch, which takes several seconds
                 and is not otherwise needed to produce the table.

The Python reference number quoted in the C2 brief is ~10.2k pos/s. Pass
--python to re-measure it on this machine rather than trusting that figure, and
transcribe both halves of the ratio into BENCH.md together — a speedup quoted
against someone else's baseline is not a measurement.
"""

import argparse
import platform
import sys
import time
from pathlib import Path

import numpy as np

# pytest.ini's `pythonpath = .` only applies under pytest, so make the built
# extension importable however this script is invoked.
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

import guofish_core  # noqa: E402

GOLDEN = REPO_ROOT / "golden" / "tokens.npz"


def load_fens(limit):
    if not GOLDEN.exists():
        sys.exit(f"{GOLDEN} not found; it is generated by tools/gen_token_golden.py")
    with np.load(GOLDEN, allow_pickle=True) as archive:
        fens = [str(f) for f in archive["fens"]]
    return fens[:limit] if limit else fens


def bench_fill(fens, repeats):
    """Wall-clock throughput of the end-to-end batch call. Best of `repeats`."""
    batch = guofish_core.TokenBatch(len(fens))

    best = float("inf")
    for _ in range(repeats):
        start = time.perf_counter()
        written = batch.fill(fens)
        elapsed = time.perf_counter() - start
        assert written == len(fens)
        best = min(best, elapsed)

    # Prove the buffer actually holds an encoding rather than zeros; a fill()
    # that silently did nothing would otherwise post an excellent number.
    view = batch.view()
    assert (view[:, 67] == 40).all(), "CLS column is not 40; fill() did not encode"

    return len(fens) / best


def bench_python(fens, repeats):
    """The reference implementation, on this machine. Imports torch."""
    import chess
    from core.mctsv4 import board_to_tokens

    # Warm up: the first call pays torch's lazy initialisation.
    board_to_tokens(chess.Board(fens[0]))

    best = float("inf")
    for _ in range(repeats):
        start = time.perf_counter()
        for fen in fens:
            board_to_tokens(chess.Board(fen))
        best = min(best, time.perf_counter() - start)

    return len(fens) / best


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--repeats", type=int, default=5,
                        help="passes over the corpus; the best is reported")
    parser.add_argument("--limit", type=int, default=0,
                        help="use only the first N FENs (0 = all)")
    parser.add_argument("--python", action="store_true",
                        help="also time core.mctsv4.board_to_tokens (imports torch)")
    args = parser.parse_args()

    fens = load_fens(args.limit)
    info = guofish_core.build_info()

    print(f"platform : {platform.system()} {platform.machine()}")
    print(f"python   : {platform.python_version()} ({sys.implementation.name})")
    print(f"build    : {info['compiler']}, asan={info['asan']}, ubsan={info['ubsan']}, "
          f"asserts={info['asserts']}")
    print(f"corpus   : {len(fens)} FENs from {GOLDEN.name}")
    print(f"repeats  : {args.repeats}")
    if info["asan"]:
        print()
        print("WARNING: this is a sanitizer build. Do not transcribe these numbers into")
        print("         BENCH.md as the production figure (README_BUILD.md, Benchmarks).")
    print()

    # Warm up the encoder so the first timed pass is not paying page faults on
    # the freshly allocated scratch buffer.
    guofish_core.tokenize_bench(fens[:1000], 5)

    encoder = guofish_core.tokenize_bench(fens, args.repeats)
    fill = bench_fill(fens, args.repeats)

    rows = [
        ("encoder (tokenize_bench)", encoder["positions_per_second"], encoder["ns_per_position"]),
        ("batch (TokenBatch.fill)", fill, 1e9 / fill),
    ]
    if args.python:
        reference = bench_python(fens, max(1, args.repeats // 2))
        rows.append(("python (board_to_tokens)", reference, 1e9 / reference))
    else:
        reference = None

    print("| path | positions/s | ns/position |")
    print("|---|---:|---:|")
    for label, pps, nsp in rows:
        print(f"| {label} | {pps:,.0f} | {nsp:,.1f} |")

    print()
    if reference is not None:
        print(f"speedup vs the reference measured here ({reference:,.0f} pos/s): "
              f"encoder {encoder['positions_per_second'] / reference:.1f}x, "
              f"fill {fill / reference:.1f}x")
    print(f"speedup vs the 10,200 pos/s quoted in the C2 brief: "
          f"encoder {encoder['positions_per_second'] / 10_200:.1f}x, "
          f"fill {fill / 10_200:.1f}x")

    target = 100 * 10_200
    verdict = "PASS" if encoder["positions_per_second"] >= target else "FAIL"
    print(f"gate: encoder {encoder['positions_per_second']:,.0f} pos/s vs "
          f"{target:,} pos/s (100x) -> {verdict}")


if __name__ == "__main__":
    main()
