"""Generate the Gate 1 golden data — the replay dump and reference trees.

`python-chess` plus `core.mctsv4` plus the v5 checkpoint are the *reference
implementation* (Global Rule 2). The C++ search is judged against these files;
these files are never regenerated to agree with C++. Nothing here imports
`guofish_core`, and the `nn_key` used to index the dump is computed by the pure
Python FNV-1a in tools/gen_key_golden.py, not by the implementation under test.

Usage:
    python tools/gen_gate1_golden.py                        # C5's quiet corpus
    python tools/gen_gate1_golden.py --corpus terminal      # C6's terminal corpus
    python tools/gen_gate1_golden.py --positions 2 --sims 200 --smoke
    python tools/gen_gate1_golden.py --force                # overwrite existing

TWO CORPORA, TWO SETS OF FILES
-------------------------------------------------------------------------------
`--corpus quiet` (the default) is C5's: game-realistic midgame positions sampled
from the benchmark PGNs and *rejected* if the reference search touches a
terminal, draw or depth-cap path. It writes golden/gate1_{dump,trees,manifest}.

`--corpus terminal` is C6's: a hand-specified corpus that exists to touch exactly
that machinery — forced mates in range, stalemate traps, threefold repetitions,
positions at halfmove clock >= 90, insufficient material, and lines that hit the
depth cap. It writes golden/gate1_terminal_{dump,trees,manifest} and never
touches the quiet files, so C5's acceptance data is not regenerated by a C6 run
(Global Rules 1 and 2).

The two differ in one more way that matters. The quiet generator AUDITS AND
REJECTS: a candidate whose tree shows a terminal is discarded. The terminal
generator AUDITS AND RECORDS: every terminal, draw, cap hit and early exit is
counted into the manifest, and the acceptance test asserts the corpus covers each
class. "This corpus exercises stalemate" is then a number in a file rather than a
sentence in a commit message.

-------------------------------------------------------------------------------
What Gate 1 is, and what the replay evaluator is for
-------------------------------------------------------------------------------
Gate 1 asks one question: does the C++ traverse loop -- PUCT selection,
expansion, virtual-loss bookkeeping, backup -- do bit-for-bit what the Python
one does? It deliberately does NOT ask whether C++ can reproduce ATen's softmax,
because it cannot: ATen's CPU path uses a vectorised exp (SLEEF/AVX), not
libm's, so a hand-rolled C++ softmax differs in the last ulp and the divergence
compounds through selection.

So the network is taken out of the loop. Python runs once, with the real
checkpoint, and dumps

    nn_key -> (legal moves in canonical order, priors in canonical order, value)

for every position it expanded. C++ replays that dump as its evaluator. The NN
side is then identical *by construction*, and any divergence is provably in
selection, backup, virtual loss or ordering -- the only thing this gate was ever
meant to test.

The dump is also a test in its own right, and the strongest one in the chunk.
C++ reaches positions by `makeMove` from the root, tokenizes the resulting
search state, and hashes those tokens into an `nn_key`. If its in-search
tokenization derives so much as a different en-passant square, the key it
computes is not a key this file contains, and the lookup misses. A miss is a
hard, named failure on the C++ side -- never a default value -- so the replay
lookup audits in-search tokenization for free.

-------------------------------------------------------------------------------
The equivalence configuration, and why each knob is set the way it is
-------------------------------------------------------------------------------
    1 worker            the gate is about tree logic, not concurrency.
    cache_size=1        NOT cache-off. `cache_size=0` raises IndexError
                        (mctsv4.py TranspositionCache.put indexes a zero-length
                        ring) and no cache-off flag exists. With the tablebase
                        off the cache is result-invariant -- it stores raw
                        logits, and expand() softmaxes them identically whether
                        they arrived from the network or the ring -- so a
                        one-slot ring is a valid neutralisation rather than a
                        workaround. It is cleared before every run here anyway.
    tablebase off       a tablebase value would replace the network's, and the
                        dump would then be recording a value C++ has no way to
                        derive. Out of scope until C7.
    Dirichlet off       noise is random; there is nothing to reproduce.
    GATE1_CANONICAL_ORDER=True
                        see core/mctsv4.py. Children are permuted into canonical
                        (from, to, promotion) order AFTER the softmax, never by
                        sorting the move list before it.

VIRTUAL_LOSS is swept over two values and both are written:

    0.0   the isolation setting. Virtual loss contributes nothing to selection,
          so a failure here is not a virtual-loss failure.
    2.5   the production magnitude, and the semantically representative run.
          `select_child` reads the parent's `effective_visits`, and the parent
          always carries one applied virtual loss mid-descent, so even at one
          worker `parent_visits = N + 1*VL`. Single-threaded Python is still
          deterministic at 2.5, so this must also be bit-exact -- and it is the
          only place virtual loss's apply/repay ordering is exercised before
          concurrency lands in C9.

-------------------------------------------------------------------------------
"Quiet" is a measured property, not an assumption
-------------------------------------------------------------------------------
C5 excludes terminal handling: no checkmate, no stalemate, no repetition, no
fifty-move, no depth cap. That is only safe if the corpus genuinely contains
none of those *within search range*, which is not something position selection
can promise -- a quiet-looking middlegame can still hold a mate in 6 that 5,000
simulations will find.

So every candidate is run first and audited afterwards, and only positions whose
reference run touched none of the excluded machinery are kept. The audit walks
the finished tree and requires, for every node with visit_count > 0:

    is_terminal is False        no checkmate/stalemate/repetition/fifty-move
    is_expanded and children    a visited node that is neither expanded nor
                                terminal is precisely the depth-cap signature
    depth < MAX_TREE_DEPTH      belt and braces on the same thing

plus a direct counter on `_draw_by_rule` returning True. A candidate failing any
of these is discarded with its reason recorded in the manifest, so the rejects
are auditable rather than invisible.

-------------------------------------------------------------------------------
Output
-------------------------------------------------------------------------------
`golden/gate1_dump.npz` -- the replay evaluator dump, CSR-packed:

    keys          uint64[E]    nn_key, ascending, unique
    move_offset   uint64[E+1]  CSR row starts into moves/priors
    moves         uint16[M]    packed (from << 10 | to << 4 | promo), canonical
                               order, over the NORMALISED UCI destination
    priors        float32[M]   post-softmax priors, already permuted into that
                               same canonical order -- C++ reads them directly
                               and performs no softmax in this chunk
    values        float64[E]   the network's ABSOLUTE (White-POV) value

    Priors are float32 because that is what they already are: expand() softmaxes
    a float32 tensor, so every prior is the exact double promotion of a float32
    and storing the narrower type is lossless. Asserted per value, not assumed.

`golden/gate1_trees.npz` -- the reference tree serialisations, CSR-packed by run:

    run_offset    uint64[R+1]  CSR row starts into the per-node arrays
    depth         uint16[T]    plies from the root; the root is 0
    move          uint16[T]    packed move that reaches this node; 0 at the root
    visits        int32[T]
    value_sum     float64[T]   bit-exact; this is the accumulator being compared
    prior         float32[T]
    children      uint16[T]    number of children the node has
    terminal      uint8[T]     node.is_terminal
    terminal_value float32[T]  node.terminal_value

    Nodes are in canonical DFS preorder. The 5,000-simulation runs record the
    VISITED subtree (visit_count > 0); the separate full-tree control runs record
    every node including unvisited children. See --full-tree-sims below for why
    both exist.

    `terminal` / `terminal_value` are C6's and are written by both corpora; the
    quiet files predate them and simply do not carry the columns, which the C6
    test reads as "all zero" — a claim it then asserts against the C++ side
    rather than assuming.

`golden/gate1_manifest.json` -- provenance (interpreter, library versions, model
SHA-256, seed, arguments), the position list, the per-run configuration and the
quietness audit counters. Human-readable; the npz files are not.
"""

import argparse
import hashlib
import json
import platform
import struct
import sys
import time
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parent.parent
TOOLS_DIR = Path(__file__).resolve().parent
for _p in (str(REPO_ROOT), str(TOOLS_DIR)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

import chess  # noqa: E402
import chess.pgn  # noqa: E402
import torch  # noqa: E402

from core import mctsv4  # noqa: E402
from core.mctsv4 import (BatchedEvaluator, MCTSNode, ParallelMCTS,  # noqa: E402
                         SearchParams)
# The one definition of nn_key in the project's Python half. Imported rather
# than re-implemented so the dump cannot be indexed by a key that has drifted
# from the one C3's golden data was built with. Pure Python (Global Rule 2):
# nothing in this file imports guofish_core.
from gen_key_golden import NN_TAG, fnv1a64  # noqa: E402
from gen_key_golden import fen_of  # noqa: E402
from gen_key_golden import nn_key as py_nn_key  # noqa: E402
from playing.v5.playv5 import load_model  # noqa: E402

DEFAULT_PGN = (REPO_ROOT / "benchmarking" / "engine" / "games" / "v5" /
               "guofishv5_10.9M_2ksims_2600sf_fixednodes.pgn")
DEFAULT_MODEL = REPO_ROOT / "models" / "guofish5_20M" / "v5_10.9M_best.pt"
DEFAULT_DUMP = REPO_ROOT / "golden" / "gate1_dump.npz"
DEFAULT_TREES = REPO_ROOT / "golden" / "gate1_trees.npz"
DEFAULT_MANIFEST = REPO_ROOT / "golden" / "gate1_manifest.json"

TERMINAL_DUMP = REPO_ROOT / "golden" / "gate1_terminal_dump.npz"
TERMINAL_TREES = REPO_ROOT / "golden" / "gate1_terminal_trees.npz"
TERMINAL_MANIFEST = REPO_ROOT / "golden" / "gate1_terminal_manifest.json"

# The two virtual-loss magnitudes every position is run at. Order matters only
# in that the manifest records it; both are required by the acceptance criteria.
VIRTUAL_LOSSES = (0.0, 2.5)

PROMO_CODE = {None: 0, chess.BISHOP: 1, chess.KNIGHT: 2, chess.QUEEN: 3, chess.ROOK: 4}


# ---------------------------------------------------------------------------
# The C6 terminal corpus
# ---------------------------------------------------------------------------
#
# Hand-specified rather than sampled, because the thing being tested is rare on
# purpose: C5's audit rejected seven of twenty-seven benchmark midgames for
# touching *any* of this machinery, which is the rate at which it turns up by
# accident. A corpus that relied on finding it would be a corpus that mostly did
# not.
#
# EVERY POSITION ARISES FROM LEGAL MOVES, in the sense the brief means. The
# concern it names is the `has_legal_en_passant` boundary from C3: a hand-written
# FEN can claim an en-passant square that no legal double push could have set, and
# `rep_key` and `nn_key` then disagree about the position in a way no real game
# reaches. Two things close that here and both are asserted by
# tests/test_c6_gate1_full.py:
#
#   * every base FEN's en-passant field is `-`, so there is no ep square to be
#     inconsistent about, and each base is checked with `Board.is_valid()`;
#   * every position the search then reaches is reached by pushing a LEGAL move,
#     so its ep square is whatever python-chess's own `push()` set — which is the
#     raw rule by construction, and the one the C++ side derives.
#
# The halfmove clock IS written by hand on the fifty-move specs. That is a
# different thing from the ep field: the clock is not cross-checked against
# anything, no key reads it, and a FEN carrying `92` is exactly as consistent as
# one carrying `0`. Reaching 92 by playing 92 reversible moves would cost ninety
# lines of move list to produce the same position.
#
# Each spec is (name, categories, base_fen, moves, sims, max_tree_depth). `moves`
# are pushed from the base to build the root, which is what gives the root a move
# stack and therefore a repetition history — `build_repetition_history` walks that
# stack, and a threefold inside search range is otherwise nearly unreachable.

# The depth cap needs its own explanation; see DECISIONS.md, C6.
#
# MAX_TREE_DEPTH is 80. A line that reaches ply 80 without first repeating a
# position or crossing the fifty-move clock has to be 40 moves of non-repeating,
# clock-resetting play, and MCTS does not build one inside 5,000 simulations —
# every attempt at a natural depth-80 hit ended as a threefold at ply 4 or a
# fifty-move draw at ply 6, because those are what deep shuffling actually
# produces. So the cap is exercised by LOWERING IT, on both sides, and recording
# the value in the manifest: the reference reads `mctsv4.MAX_TREE_DEPTH` at each
# descent step and the C++ side reads `SearchConfig.max_tree_depth`, so a run at
# 6 executes exactly the same code path a run at 80 would, with a constant that
# is reachable. That the constant's DEFAULT is 80 on both sides is a separate
# check and is asserted separately.
# A quiet midgame at 5,000 simulations reaches depth 10-19 (measured, in the C5
# manifest), so the caps below are set well inside that: at 4, 5, 6 and 8 the cap
# fires in the first few hundred simulations rather than only at the very end of
# the run, and the resulting tree is a saturated cone whose entire frontier is
# capped nodes.
DEPTH_CAP_SIMS = 2000
DEPTH_CAPS = (4, 5, 6, 7)

TERMINAL_POSITIONS = [
    # --- forced mate in range, at depth 1: the short-circuit hack -----------
    ("mate1-backrank", ["mate1"], "6k1/5ppp/8/8/8/8/5PPP/R5K1 w - - 0 1", [], 5000, 80),
    ("mate1-queen", ["mate1"], "6k1/5ppp/8/8/8/8/6PP/3Q2K1 w - - 0 1", [], 5000, 80),
    ("mate1-rook-kr", ["mate1"], "7k/8/6K1/8/8/8/8/R7 w - - 0 1", [], 5000, 80),

    # --- forced mate in range, deeper: terminals with no short-circuit ------
    ("mate2-rooks-ladder", ["mate2", "stalemate"], "8/8/8/8/1R6/k7/7R/7K w - - 0 1", [], 5000, 80),
    ("mate2-rooks-pair", ["mate2", "stalemate"], "2K5/8/8/8/1R4R1/8/8/k7 w - - 0 1", [], 5000, 80),
    ("mate2-queen", ["mate2"], "8/3Q4/8/8/8/3K4/8/2k5 w - - 0 1", [], 5000, 80),
    ("mate2-queen-knight", ["mate2"], "8/5k2/6NK/1Q6/8/8/8/8 w - - 0 1", [], 5000, 80),
    ("mate3-bishop-queen", ["mate3", "stalemate"], "1K1k4/8/8/8/8/4B2Q/8/8 w - - 0 1", [], 5000, 80),
    ("mate3-queen-rook", ["mate3"], "8/8/8/6k1/8/2KQ4/8/R7 w - - 0 1", [], 5000, 80),
    ("mate3-rook-queen", ["mate3"], "3RQ3/8/8/8/6K1/8/2k5/8 w - - 0 1", [], 5000, 80),

    # --- stalemate traps ---------------------------------------------------
    # No mate in one in any of these, so the search is not truncated before the
    # stalemating move is tried; every root child is visited early at FPU_ROOT 0.
    ("stalemate-queen-h1", ["stalemate"], "7k/8/8/8/8/8/5Q2/7K w - - 0 1", [], 5000, 80),
    ("stalemate-queen-f1", ["stalemate"], "7k/8/8/8/8/8/6Q1/5K2 w - - 0 1", [], 5000, 80),
    ("stalemate-queen-c1", ["stalemate"], "k7/8/8/8/8/8/2Q5/2K5 w - - 0 1", [], 5000, 80),

    # --- insufficient material --------------------------------------------
    # The root is NOT insufficient (the opponent's knight/bishop makes the
    # bishop and knight clauses answer False); one capture makes it so.
    ("insufficient-kb", ["insufficient"], "8/8/8/6k1/4n3/3K4/8/7B w - - 0 1", [], 5000, 80),
    ("insufficient-kn", ["insufficient"], "8/8/8/6k1/3Kb3/8/8/2N5 w - - 0 1", [], 5000, 80),

    # --- threefold repetition ---------------------------------------------
    # The four shuffle moves put the ROOT POSITION in its own repetition history
    # twice (`build_repetition_history` counts the root as 1 and then walks back
    # over the four plies, meeting it again). One recurrence inside a simulation
    # line then makes three, which a drawn endgame reaches within four plies.
    ("threefold-blocked-pawns", ["threefold"], "8/8/1p1k4/1P6/8/3K4/8/8 w - - 0 1",
     ["d3e3", "d6e6", "e3d3", "e6d6"], 5000, 80),
    # Eight plies rather than four, i.e. TWO loops. That primes the history of
    # every position on the loop to 2, not only the root's, so a threefold is
    # reachable one ply into a simulation instead of only four. The four-ply
    # priming was measured not to fire at all here at 1,500 simulations: the
    # branching (five to fourteen moves a side) is wide enough that MCTS simply
    # never closed a four-ply loop, and a spec that does not fire is a spec that
    # is not testing anything.
    ("threefold-pawn-chain", ["threefold"], "4k3/8/8/3pP3/3P4/8/8/4K3 w - - 0 1",
     ["e1e2", "e8e7", "e2e1", "e7e8", "e1e2", "e8e7", "e2e1", "e7e8"], 5000, 80),
    # Bishops on OPPOSITE complexes. On the same complex the position is
    # insufficient material and the root is already over -- `has_insufficient_material`
    # answers the same-colour question against BOTH sides' bishops, which is the
    # quirk cpp/terminal.hpp transcribes and the first draft of this spec walked
    # straight into.
    ("threefold-opp-bishops", ["threefold"], "4k3/8/8/2b5/8/5B2/8/4K3 w - - 0 1",
     ["e1e2", "e8e7", "e2e1", "e7e8", "e1e2", "e8e7", "e2e1", "e7e8"], 5000, 80),

    # --- the fifty-move rule ----------------------------------------------
    # The clock crosses 100 at ply 6, 6 and 8 respectively, which is well inside
    # the tree at 5,000 simulations.
    ("fifty-blocked-pawns", ["fifty"], "8/8/1p1k4/1P6/8/3K4/8/8 w - - 92 60",
     ["d3e3", "d6e6"], 5000, 80),
    ("fifty-pawn-chain", ["fifty"], "4k3/8/8/3pP3/3P4/8/8/4K3 w - - 94 70",
     ["e1e2", "e8e7"], 5000, 80),
    # Rooks that CANNOT take each other, in a dead-drawn R+K vs R+K.
    #
    # The first draft had them facing on the d-file at clock 90, and it produced
    # not one fifty-move hit in 1,500 simulations. The reason is worth recording,
    # because it is a property of MCTS rather than of the rule: Rxd8 wins a rook,
    # its prior is near 1 and its Q near +0.9, and at FPU_ROOT 0.0 an unvisited
    # sibling scores c*P*sqrt(N)/1 ~ 0.05. The winning capture is never
    # displaced, so every simulation went down it, the clock was zeroed at ply
    # one every time, and the other nineteen root moves were never visited at
    # all. A spec meant to exercise a rule must not contain a move that eats the
    # whole search.
    ("fifty-rooks", ["fifty"], "4rk2/8/8/8/8/8/8/3R1K2 w - - 94 70",
     ["d1d2", "e8e7"], 5000, 80),

    # --- the depth cap -----------------------------------------------------
    # Quiet midgames from the C5 corpus, which the C5 audit already certified as
    # reaching no terminal and no draw. With the cap lowered, the ONLY thing they
    # can exercise is the cap — so a depth-cap hit here cannot be confused with a
    # terminal, and a terminal here would be a failure of the C5 certification.
    ("depthcap-04", ["depthcap"],
     "r1bq1rk1/pp2ppbp/2np1np1/8/2PNP3/2N1B3/PP2BPPP/R2Q1RK1 w - - 0 1", [],
     DEPTH_CAP_SIMS, DEPTH_CAPS[0]),
    ("depthcap-05", ["depthcap"],
     "r2q1rk1/pb1nbppp/1p2pn2/2pp4/2PP4/1PN1PN2/PB2BPPP/R2Q1RK1 w - - 0 1", [],
     DEPTH_CAP_SIMS, DEPTH_CAPS[1]),
    ("depthcap-06", ["depthcap"],
     "r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 0 1", [],
     DEPTH_CAP_SIMS, DEPTH_CAPS[2]),
    ("depthcap-07", ["depthcap"],
     "rnbq1rk1/ppp1ppbp/3p1np1/8/2PPP3/2N2N2/PP2BPPP/R1BQK2R w KQ - 0 1", [],
     DEPTH_CAP_SIMS, DEPTH_CAPS[3]),
]

# Every class the brief names must be covered by at least one accepted run, and
# the acceptance test re-checks this against the MEASURED counters rather than
# against these labels.
REQUIRED_CATEGORIES = ("mate1", "mate2", "mate3", "stalemate", "insufficient",
                       "threefold", "fifty", "depthcap")


# ---------------------------------------------------------------------------
# Packing — must agree with cpp/arena.hpp
# ---------------------------------------------------------------------------

def pack_move(move: chess.Move) -> int:
    """(from, to, promotion) packed into the uint16 the C++ arena stores.

    from << 10 | to << 4 | promo, squares numbered rank*8 + file (python-chess's
    numbering, which is also chess-library's). The promotion codes are
    ALPHABETICAL by UCI letter -- b=1, n=2, q=3, r=4, none=0 -- not by piece
    value, so that sorting on the derived canonical key reproduces byte order on
    the UCI string. See cpp/arena.hpp.

    python-chess's generators already emit standard (non-Chess960) castling
    moves, so `move.to_square` is the king's destination (g1/c1), not the rook's.
    That is the normalised destination C1 established and the one the C++ side
    sorts on.
    """
    promo = PROMO_CODE[move.promotion]
    return (move.from_square << 10) | (move.to_square << 4) | promo


def canonical_key(packed: int) -> int:
    """Sort key whose integer order is byte order on the move's UCI string.

    Square indices are rank-major (a1, b1, ... h1, a2) while UCI string order is
    file-major (a1, a2, ... a8, b1), so sorting packed moves directly is NOT
    canonical order. Mirrors guofish::canonical_move_key.
    """
    frm = (packed >> 10) & 0x3F
    to = (packed >> 4) & 0x3F
    promo = packed & 0x0F
    return (((frm & 7) << 13) | ((frm >> 3) << 10) | ((to & 7) << 7) |
            ((to >> 3) << 4) | promo)


# ---------------------------------------------------------------------------
# nn_key
# ---------------------------------------------------------------------------

def nn_key_from_tokens(tokens: torch.Tensor) -> int:
    """`nn_key` over a token tensor, i.e. over the exact bytes the network saw.

    The evaluator is intercepted at the point where it holds `EvalRequest.tokens`,
    which is what `board_to_tokens` produced for that leaf. Hashing the tensor
    rather than re-deriving a board removes any chance that the value recorded
    for a key was computed for a different position -- the same one-source
    discipline scope 2.5 imposes on the C++ cache.
    """
    arr = np.asarray(tokens.detach().to("cpu")).astype("<i4")
    assert arr.shape == (mctsv4.SEQ_LENGTH,), f"tokenizer returned {arr.shape}"
    return fnv1a64(NN_TAG + arr.tobytes())


# ---------------------------------------------------------------------------
# Recording
# ---------------------------------------------------------------------------

class Recorder:
    """Collects the replay dump across every run of the session.

    `values` is filled by intercepting the evaluator, `entries` by walking each
    finished tree. They are joined on nn_key and cross-checked: a key present in
    one and not the other means the tokenization the evaluator saw and the one
    the walk derives disagree, which would silently corrupt the dump.
    """

    def __init__(self):
        self.values: dict[int, float] = {}
        # Keyed by (nn_key, is_root) -- NOT by nn_key alone. See record_entry.
        self.entries: dict[tuple[int, bool],
                           tuple[tuple[int, ...], tuple[float, ...]]] = {}
        self.value_conflicts = 0
        self.entry_conflicts = 0

    def record_value(self, key: int, value: float) -> None:
        previous = self.values.get(key)
        if previous is None:
            self.values[key] = value
            return
        # Two evaluations of one position must agree bit-for-bit: the model is
        # deterministic and every batch is size 1 at one worker. A conflict here
        # means the run is not reproducible and the dump would be ambiguous, so
        # it aborts rather than picking a winner.
        if struct.pack("<d", previous) != struct.pack("<d", value):
            self.value_conflicts += 1
            raise AssertionError(
                f"nn_key {key:#018x} evaluated twice with different values: "
                f"{previous!r} then {value!r}. The reference run is not "
                f"deterministic; the dump cannot be written.")

    def record_entry(self, key: int, is_root: bool, moves: tuple[int, ...],
                     priors: tuple[float, ...]) -> None:
        """Record one expansion's canonical children.

        THE `is_root` FLAG IS NOT BOOKKEEPING. The reference softmaxes root
        priors and interior priors on DIFFERENT DEVICES, and the two disagree:

          _expand_root  runs its own forward and passes `policy_logits[0]`
                        straight to expand() while it is still a CUDA tensor, so
                        the gather, the .float() and the torch.softmax all run
                        on the GPU.
          interior      BatchedEvaluator._evaluate_batch does a bulk .cpu()
                        before distributing, so expand() softmaxes on the CPU.

        Measured on this checkpoint and a middlegame position: 6 of 37 priors
        differ, max absolute delta 1.9e-9. That is far above the bit level Gate 1
        compares at, and it is load-bearing rather than cosmetic -- priors feed
        PUCT, so the difference propagates into visit counts.

        It only becomes visible when the root position RECURS as an interior
        node, which a middlegame reaches easily in four plies, and it did so on
        the first candidate position at 200 simulations. A dump keyed by nn_key
        alone cannot represent both, so the key is the pair.

        This is a preserved property of the reference, not a defect to fix here.
        Making _expand_root softmax on the CPU would remove it, but that is a
        change to search behaviour beyond the canonical-ordering patch the brief
        sanctions, and Gate 1 exists to reproduce the reference as it is. Flagged
        in DECISIONS.md; a candidate for C10's list, not for this chunk.
        """
        slot = (key, is_root)
        previous = self.entries.get(slot)
        if previous is None:
            self.entries[slot] = (moves, priors)
            return
        old_moves, old_priors = previous
        same = (old_moves == moves and
                all(struct.pack("<d", a) == struct.pack("<d", b)
                    for a, b in zip(old_priors, priors)))
        if not same:
            self.entry_conflicts += 1
            deltas = [abs(a - b) for a, b in zip(old_priors, priors)]
            raise AssertionError(
                f"nn_key {key:#018x} (is_root={is_root}) expanded twice with "
                f"different children: moves equal={old_moves == moves}, "
                f"max prior delta "
                f"{max(deltas) if deltas else float('nan'):.3e}")


def install_hooks(recorder: Recorder):
    """Intercept the three places a network value enters the search.

    Returns an uninstall callable. The hooks only observe -- each calls through
    to the original and reads what it produced -- so the search they wrap is the
    search the reference performs, not a variant of it.
    """
    orig_batch = BatchedEvaluator._evaluate_batch
    orig_inline = BatchedEvaluator.eval_inline
    orig_expand_root = ParallelMCTS._expand_root

    def patched_batch(self, batch):
        orig_batch(self, batch)
        for request in batch:
            if request.value is not None:
                recorder.record_value(nn_key_from_tokens(request.tokens), request.value)

    def patched_inline(self, tokens):
        policy, value = orig_inline(self, tokens)
        recorder.record_value(nn_key_from_tokens(tokens), value)
        return policy, value

    def patched_expand_root(self, root, board):
        orig_expand_root(self, root, board)
        # _expand_root runs its own unbatched forward and writes the result
        # straight into root.value_sum, already converted to the mover's
        # perspective. The conversion is a negation, so it inverts exactly.
        nn_value = root.value_sum if board.turn == chess.BLACK else -root.value_sum
        recorder.record_value(py_nn_key(board), nn_value)

    BatchedEvaluator._evaluate_batch = patched_batch
    BatchedEvaluator.eval_inline = patched_inline
    ParallelMCTS._expand_root = patched_expand_root

    def uninstall():
        BatchedEvaluator._evaluate_batch = orig_batch
        BatchedEvaluator.eval_inline = orig_inline
        ParallelMCTS._expand_root = orig_expand_root

    return uninstall


class DrawRuleCounter:
    """Counts `_draw_by_rule` returning True during a run.

    The tree audit below would catch a repetition or fifty-move draw anyway (it
    leaves a node marked terminal), but this counts the event at its source, so a
    manifest entry of 0 is a direct statement rather than an inference.
    """

    def __init__(self):
        self.hits = 0
        self._orig = mctsv4.MCTSWorker._draw_by_rule

    def __enter__(self):
        counter = self

        def patched(worker_self, board, path_counts):
            result = counter._orig(worker_self, board, path_counts)
            if result:
                counter.hits += 1
            return result

        mctsv4.MCTSWorker._draw_by_rule = patched
        return self

    def __exit__(self, *exc):
        mctsv4.MCTSWorker._draw_by_rule = self._orig
        return False


# ---------------------------------------------------------------------------
# Tree walk
# ---------------------------------------------------------------------------

class QuietnessFailure(Exception):
    """A candidate position touched machinery C5 does not implement."""


def walk_tree(root: MCTSNode, root_board: chess.Board, recorder: Recorder,
              *, visited_only: bool, strict: bool = True):
    """Canonical DFS preorder over the tree, collecting records and dump entries.

    Iterative rather than recursive: MAX_TREE_DEPTH is 80 so recursion would in
    fact be safe, but the audit below has to be able to *report* a depth
    violation rather than hit a RecursionError on the way to it.

    `strict` selects between the two corpora's audits, and the difference is the
    whole distinction between them. With strict=True (C5) the walk RAISES
    QuietnessFailure at the first sign of the terminal, draw or depth-cap
    machinery, so the position is rejected. With strict=False (C6) it COUNTS the
    same signs into `census` and keeps going, so the manifest can state what the
    corpus exercised.
    """
    records: list[tuple[int, int, int, float, float, int, int, float]] = []
    board = root_board.copy(stack=False)
    max_depth = 0
    expanded_nodes = 0
    census = {
        "terminal_nodes": 0,
        "terminal_win": 0,       # terminal_value == 1.0 -- checkmate, mover won
        "terminal_draw": 0,      # terminal_value == 0.0 -- stalemate/draw/rule
        "terminal_loss": 0,      # terminal_value == -1.0; unreachable, counted anyway
        "unexpanded_visited": 0,  # the depth-cap signature, or a claimable draw
        "terminal_with_children": 0,  # THE bestmove-0000 STATE. Must stay 0.
        "at_depth_cap": 0,
    }

    # (node, depth, packed move that reached it, iterator over children, pushed?)
    # A hand-rolled stack of frames; `pending` is the reversed child list so
    # pop() yields canonical order.
    stack: list[tuple[MCTSNode, int, int, list]] = []

    def visit(node: MCTSNode, depth: int, packed: int) -> None:
        nonlocal max_depth, expanded_nodes
        if depth > max_depth:
            max_depth = depth

        if node.visit_count > 0:
            if node.is_terminal:
                if strict:
                    raise QuietnessFailure(
                        f"node at depth {depth} is terminal (value "
                        f"{node.terminal_value}) -- checkmate, stalemate, "
                        f"repetition or fifty-move is in range")
                census["terminal_nodes"] += 1
                if node.terminal_value == 1.0:
                    census["terminal_win"] += 1
                elif node.terminal_value == 0.0:
                    census["terminal_draw"] += 1
                else:
                    census["terminal_loss"] += 1
                if node.children:
                    # The reference CAN reach this: the is_game_over path sets
                    # is_expanded on a node whose children dict is empty, and a
                    # later _expand_root on the same node would fill it. It
                    # cannot happen inside one search, and the C++ arena cannot
                    # represent it at all -- so a non-zero count here would mean
                    # the reference had done something C++ is structurally
                    # unable to copy, which is worth knowing loudly.
                    census["terminal_with_children"] += 1
            elif not node.is_expanded or not node.children:
                if strict:
                    raise QuietnessFailure(
                        f"node at depth {depth} has {node.visit_count} visits but "
                        f"is not expanded -- this is the depth-cap signature")
                census["unexpanded_visited"] += 1
            # Gated on visit_count because an UNVISITED child at depth 80 is
            # merely a node the search never entered, whereas a visited one at
            # that depth is the cap having fired. Only the second is a reason to
            # reject the position.
            if depth >= mctsv4.MAX_TREE_DEPTH:
                if strict:
                    raise QuietnessFailure(
                        f"tree reached depth {depth} >= MAX_TREE_DEPTH "
                        f"({mctsv4.MAX_TREE_DEPTH}) with visits")
                census["at_depth_cap"] += 1

        records.append((depth, packed, node.visit_count, node.value_sum,
                        node.prior, len(node.children),
                        1 if node.is_terminal else 0, node.terminal_value))

        if node.children:
            expanded_nodes += 1
            moves = tuple(pack_move(m) for m in node.children)
            priors = tuple(c.prior for c in node.children.values())
            # The order the search actually holds them in must already be
            # canonical; the flag patch is what guarantees it. Checking rather
            # than sorting here is deliberate -- sorting would paper over a
            # patch that failed to apply, and the whole dump would then be
            # ordered differently from the tree it came from.
            keys = [canonical_key(m) for m in moves]
            if keys != sorted(keys):
                raise AssertionError(
                    "children are not in canonical order; is "
                    "mctsv4.GATE1_CANONICAL_ORDER set?")
            recorder.record_entry(nn_key_of_board(board), depth == 0, moves,
                                  priors)

    def children_frames(node: MCTSNode) -> list:
        out = []
        for move, child in node.children.items():
            if visited_only and child.visit_count == 0:
                continue
            out.append((move, child))
        out.reverse()
        return out

    def nn_key_of_board(b: chess.Board) -> int:
        return py_nn_key(b)

    visit(root, 0, 0)
    stack.append((root, 0, 0, children_frames(root)))

    while stack:
        node, depth, packed, pending = stack[-1]
        if not pending:
            stack.pop()
            if stack:
                board.pop()
            continue
        move, child = pending.pop()
        board.push(move)
        visit(child, depth + 1, pack_move(move))
        child_pending = children_frames(child)
        if child_pending:
            stack.append((child, depth + 1, pack_move(move), child_pending))
        else:
            board.pop()

    return records, max_depth, expanded_nodes, census


# ---------------------------------------------------------------------------
# Position selection
# ---------------------------------------------------------------------------

def candidate_positions(pgn_path: Path, *, seed: int, min_ply: int, max_ply: int,
                        min_pieces: int, max_candidates: int):
    """Quiet-looking midgame positions, one per game, in a deterministic order.

    Game-realistic rather than constructed: scope 3 says the ~400 benchmark games
    are sufficient for everything needing realistic positions, and constructing
    midgames by hand would bias the corpus toward whatever the author thinks a
    midgame looks like. The filters below only remove positions that are
    obviously unusable; the real acceptance test is the reference run itself.
    """
    rng = np.random.default_rng(seed)
    out = []
    with open(pgn_path, encoding="utf-8", errors="replace") as handle:
        while len(out) < max_candidates:
            game = chess.pgn.read_game(handle)
            if game is None:
                break
            moves = list(game.mainline_moves())
            if len(moves) < max_ply + 8:
                continue
            board = game.board()
            ply_choice = int(rng.integers(min_ply, max_ply + 1))
            ok = True
            for i, move in enumerate(moves):
                if i >= ply_choice:
                    break
                board.push(move)
            else:
                ok = False
            if not ok:
                continue

            if board.is_game_over():
                continue
            if board.is_check():
                # Not because checks are unsupported -- they are ordinary
                # positions -- but because a position in check is materially
                # more likely to have a forced mate inside 5,000 simulations,
                # and every such candidate costs a full reference run to reject.
                continue
            if chess.popcount(board.occupied) < min_pieces:
                continue
            if board.halfmove_clock > 6:
                continue
            if len(list(board.legal_moves)) < 10:
                continue
            history = mctsv4.build_repetition_history(board)
            if max(history.values()) > 1:
                continue
            # Re-derive the position from its own FEN, dropping the move stack.
            #
            # Two things depend on this. `build_repetition_history` walks the
            # stack, so a position carrying one would search against a game
            # history the C++ side (which is handed a FEN) does not have --
            # the run would not be reproducible from what the manifest records.
            # And the FEN is written with en_passant="fen", so the ep square
            # survives a double push with no legal capture; python-chess's
            # DEFAULT fen() omits it, which would move token 66 and therefore
            # the nn_key on ~3% of positions. See DECISIONS.md, C2.
            out.append((game.headers.get("White", "?"),
                        game.headers.get("Black", "?"),
                        ply_choice, chess.Board(fen_of(board))))
    return out


# ---------------------------------------------------------------------------
# Runs
# ---------------------------------------------------------------------------

def run_reference(mcts: ParallelMCTS, board: chess.Board, sims: int,
                  recorder: Recorder, *, visited_only: bool, strict: bool = True):
    """One reference search, audited. Returns (records, audit) or raises.

    `strict` is the corpus distinction; see walk_tree. In the strict case every
    audit below is a rejection criterion, so a returned audit means the position
    touched nothing C5 excludes. In the non-strict case the same facts are
    recorded into the audit and the position is kept.
    """
    mcts.reset()
    mcts.clear_cache()

    with DrawRuleCounter() as draws:
        started = time.perf_counter()
        best = mcts.search(board.copy(), num_simulations=sims)
        elapsed = time.perf_counter() - started

    if best is None:
        # Only a root with no legal moves produces this, and neither corpus
        # contains one: a finished game has no move to search for.
        raise QuietnessFailure("search returned no move")
    if strict and draws.hits:
        raise QuietnessFailure(f"_draw_by_rule fired {draws.hits} times")

    root = mcts.root
    records, max_depth, expanded, census = walk_tree(
        root, board, recorder, visited_only=visited_only, strict=strict)
    early_exit = int(root.visit_count) != sims
    if strict and early_exit:
        raise QuietnessFailure(
            f"root visit_count {root.visit_count} != requested {sims}; the "
            f"search exited early")

    audit = {
        "best_move": best.uci(),
        "root_visits": int(root.visit_count),
        "nodes_recorded": len(records),
        "expanded_nodes": expanded,
        "max_depth": max_depth,
        "draw_by_rule_hits": draws.hits,
        "seconds": round(elapsed, 3),
        # C6. `early_exit` is the depth-1 mate short-circuit's fingerprint: the
        # reference stopped before reaching `sims` because a worker set
        # completion_event. Recording it is what lets the acceptance test require
        # the SAME truncation from C++, rather than quietly accepting whichever
        # tree it was handed.
        "early_exit": early_exit,
        "census": census,
    }
    return records, audit


def build_engine(model, device, cache_size: int) -> ParallelMCTS:
    return ParallelMCTS(
        model=model,
        device=device,
        num_workers=1,
        cache_size=cache_size,
        tablebase=None,
        params=SearchParams(),
    )


# ---------------------------------------------------------------------------
# Serialisation
# ---------------------------------------------------------------------------

def write_dump(path: Path, recorder: Recorder) -> dict:
    # Sorted by (nn_key, is_root) so the file has one canonical byte image for a
    # given session and a diff between two generations is readable.
    slots = sorted(recorder.entries)
    missing = [k for k, _ in slots if k not in recorder.values]
    if missing:
        raise AssertionError(
            f"{len(missing)} expanded positions have no recorded network value "
            f"(first {missing[0]:#018x}). The evaluator interception and the "
            f"tree walk disagree about nn_key.")

    move_offset = np.zeros(len(slots) + 1, dtype=np.uint64)
    moves: list[int] = []
    priors32: list[np.float32] = []
    for i, slot in enumerate(slots):
        key = slot[0]
        entry_moves, entry_priors = recorder.entries[slot]
        for packed, prior in zip(entry_moves, entry_priors):
            moves.append(packed)
            narrow = np.float32(prior)
            # The priors are already float32 -- expand() softmaxes a float32
            # tensor and .tolist() promotes exactly -- so narrowing is lossless.
            # Asserted per value rather than argued, because if it ever stopped
            # being true the golden file would silently lose the low bits that
            # Gate 1 is comparing.
            if float(narrow) != prior:
                raise AssertionError(
                    f"prior {prior!r} for nn_key {key:#018x} is not exactly "
                    f"representable as float32")
            priors32.append(narrow)
        move_offset[i + 1] = len(moves)

    np.savez_compressed(
        path,
        keys=np.array([k for k, _ in slots], dtype=np.uint64),
        is_root=np.array([1 if r else 0 for _, r in slots], dtype=np.uint8),
        move_offset=move_offset,
        moves=np.array(moves, dtype=np.uint16),
        priors=np.array(priors32, dtype=np.float32),
        values=np.array([recorder.values[k] for k, _ in slots], dtype=np.float64),
    )
    return {"entries": len(slots),
            "root_entries": sum(1 for _, r in slots if r),
            "moves": len(moves)}


def write_trees(path: Path, runs: list[dict]) -> dict:
    run_offset = np.zeros(len(runs) + 1, dtype=np.uint64)
    depth: list[int] = []
    move: list[int] = []
    visits: list[int] = []
    value_sum: list[float] = []
    prior: list[np.float32] = []
    children: list[int] = []
    terminal: list[int] = []
    terminal_value: list[np.float32] = []

    for i, run in enumerate(runs):
        for d, m, v, vs, p, c, t, tv in run["records"]:
            depth.append(d)
            move.append(m)
            visits.append(v)
            value_sum.append(vs)
            narrow = np.float32(p)
            if float(narrow) != p:
                raise AssertionError(f"prior {p!r} is not exactly float32")
            prior.append(narrow)
            children.append(c)
            terminal.append(t)
            # 1.0, 0.0 and -1.0 are the only values the reference ever writes,
            # and all three are exact in float32. Asserted rather than assumed,
            # for the same reason the priors are.
            narrow_tv = np.float32(tv)
            if float(narrow_tv) != tv:
                raise AssertionError(f"terminal_value {tv!r} is not exactly float32")
            terminal_value.append(narrow_tv)
        run_offset[i + 1] = len(depth)

    np.savez_compressed(
        path,
        run_offset=run_offset,
        depth=np.array(depth, dtype=np.uint16),
        move=np.array(move, dtype=np.uint16),
        visits=np.array(visits, dtype=np.int32),
        value_sum=np.array(value_sum, dtype=np.float64),
        prior=np.array(prior, dtype=np.float32),
        children=np.array(children, dtype=np.uint16),
        terminal=np.array(terminal, dtype=np.uint8),
        terminal_value=np.array(terminal_value, dtype=np.float32),
    )
    return {"runs": len(runs), "nodes": len(depth),
            "terminal_nodes": int(sum(terminal))}


def sha256_of(path: Path) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--corpus", choices=("quiet", "terminal"), default="quiet",
                        help="quiet = C5's sampled midgames, rejected on any "
                             "terminal/draw/cap; terminal = C6's hand-specified "
                             "corpus, which exists to hit exactly those")
    parser.add_argument("--pgn", type=Path, default=DEFAULT_PGN)
    parser.add_argument("--model", type=Path, default=DEFAULT_MODEL)
    parser.add_argument("--positions", type=int, default=20,
                        help="quiet positions to accept (brief requires >= 20)")
    parser.add_argument("--sims", type=int, default=5000,
                        help="simulations per run (brief requires >= 5000)")
    parser.add_argument("--full-tree-positions", type=int, default=4,
                        help="positions additionally recorded with EVERY node, "
                             "including unvisited children, at --full-tree-sims")
    parser.add_argument("--full-tree-sims", type=int, default=800)
    parser.add_argument("--seed", type=int, default=20260806)
    parser.add_argument("--min-ply", type=int, default=24)
    parser.add_argument("--max-ply", type=int, default=60)
    parser.add_argument("--min-pieces", type=int, default=16)
    parser.add_argument("--max-candidates", type=int, default=400)
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    parser.add_argument("--out-dump", type=Path, default=None)
    parser.add_argument("--out-trees", type=Path, default=None)
    parser.add_argument("--out-manifest", type=Path, default=None)
    parser.add_argument("--limit", type=int, default=0,
                        help="terminal corpus only: stop after N specs (smoke runs)")
    parser.add_argument("--only", default="",
                        help="terminal corpus only: comma-separated spec names to "
                             "run. For iterating on one spec; a filtered run is "
                             "not acceptance-grade.")
    parser.add_argument("--max-sims", type=int, default=0,
                        help="terminal corpus only: cap every spec's simulation "
                             "count. For smoke runs; a capped run is not "
                             "acceptance-grade and the manifest records the cap.")
    parser.add_argument("--force", action="store_true",
                        help="overwrite existing golden files")
    parser.add_argument("--smoke", action="store_true",
                        help="skip the determinism self-check (fast iteration only)")
    args = parser.parse_args()

    terminal = args.corpus == "terminal"
    if args.out_dump is None:
        args.out_dump = TERMINAL_DUMP if terminal else DEFAULT_DUMP
    if args.out_trees is None:
        args.out_trees = TERMINAL_TREES if terminal else DEFAULT_TREES
    if args.out_manifest is None:
        args.out_manifest = TERMINAL_MANIFEST if terminal else DEFAULT_MANIFEST

    outputs = [args.out_dump, args.out_trees, args.out_manifest]
    existing = [p for p in outputs if p.exists()]
    if existing and not args.force:
        print("refusing to overwrite existing golden files without --force:",
              file=sys.stderr)
        for p in existing:
            print(f"  {p}", file=sys.stderr)
        return 2

    if terminal:
        if len(TERMINAL_POSITIONS) < 20:
            print(f"ERROR: the terminal corpus has {len(TERMINAL_POSITIONS)} "
                  f"specs; the brief requires >= 20.", file=sys.stderr)
            return 1
    else:
        if args.positions < 20:
            print(f"WARNING: --positions {args.positions} is below the 20 the brief "
                  f"requires; this run is not acceptance-grade.", file=sys.stderr)
        if args.sims < 5000:
            print(f"WARNING: --sims {args.sims} is below the 5000 the brief "
                  f"requires; this run is not acceptance-grade.", file=sys.stderr)

    device = torch.device(args.device)
    model = load_model(args.model, device)

    # THE flag. Everything downstream assumes children are canonically ordered,
    # and walk_tree asserts it per node rather than trusting this line.
    mctsv4.GATE1_CANONICAL_ORDER = True

    recorder = Recorder()
    uninstall = install_hooks(recorder)
    default_max_depth = mctsv4.MAX_TREE_DEPTH
    try:
        if terminal:
            return _run_terminal(args, model, device, recorder)
        return _run(args, model, device, recorder)
    finally:
        uninstall()
        mctsv4.GATE1_CANONICAL_ORDER = False
        mctsv4.MAX_TREE_DEPTH = default_max_depth


def _run(args, model, device, recorder: Recorder) -> int:
    print(f"scanning {args.pgn}")
    candidates = candidate_positions(
        args.pgn, seed=args.seed, min_ply=args.min_ply, max_ply=args.max_ply,
        min_pieces=args.min_pieces, max_candidates=args.max_candidates)
    print(f"{len(candidates)} candidate positions pass the cheap filters")
    if len(candidates) < args.positions:
        print(f"ERROR: only {len(candidates)} candidates for "
              f"{args.positions} positions", file=sys.stderr)
        return 1

    mcts = build_engine(model, device, cache_size=1)

    accepted: list[dict] = []
    rejected: list[dict] = []
    runs: list[dict] = []

    try:
        for white, black, ply, board in candidates:
            if len(accepted) >= args.positions:
                break
            fen = fen_of(board)
            print(f"[{len(accepted) + 1}/{args.positions}] ply {ply}  {fen}",
                  flush=True)

            position_runs = []
            reason = None
            for vl in VIRTUAL_LOSSES:
                mctsv4.VIRTUAL_LOSS = vl
                try:
                    records, audit = run_reference(mcts, board, args.sims,
                                                   recorder, visited_only=True)
                except QuietnessFailure as exc:
                    reason = f"VL={vl}: {exc}"
                    break
                audit.update(virtual_loss=vl, sims=args.sims, full_tree=False)
                position_runs.append({"records": records, "audit": audit})
                print(f"      VL={vl:<4} {audit['nodes_recorded']:>7} visited "
                      f"nodes  depth<={audit['max_depth']:<3} "
                      f"{audit['seconds']:.1f}s  best={audit['best_move']}",
                      flush=True)

            if reason is not None:
                print(f"      rejected: {reason}", flush=True)
                rejected.append({"fen": fen, "ply": ply, "reason": reason})
                continue

            index = len(accepted)
            for run in position_runs:
                run["audit"].update(position=index, fen=fen)
                runs.append(run)
            accepted.append({"index": index, "fen": fen, "ply": ply,
                             "white": white, "black": black})

        if len(accepted) < args.positions:
            print(f"ERROR: accepted only {len(accepted)} of {args.positions} "
                  f"positions; {len(rejected)} rejected", file=sys.stderr)
            return 1

        # --- full-tree control runs -------------------------------------
        # The 5,000-simulation runs above record only the visited subtree: a
        # 5,000-sim tree holds ~175,000 nodes, of which ~5,000 have any visits,
        # and the rest carry visit_count 0 and value_sum 0.0 on both sides by
        # construction. Their PRIORS are not trivial, though -- they come from
        # the dump and their order is the canonical ordering under test -- so a
        # smaller run records every node, unvisited children included, and the
        # test compares that end to end. Without these the whole-tree path would
        # be argued rather than measured.
        full_tree_runs = []
        for spec in accepted[:args.full_tree_positions]:
            board = chess.Board(spec["fen"])
            print(f"[full-tree] position {spec['index']} at "
                  f"{args.full_tree_sims} sims", flush=True)
            for vl in VIRTUAL_LOSSES:
                mctsv4.VIRTUAL_LOSS = vl
                records, audit = run_reference(mcts, board, args.full_tree_sims,
                                               recorder, visited_only=False)
                audit.update(virtual_loss=vl, sims=args.full_tree_sims,
                             full_tree=True, position=spec["index"],
                             fen=spec["fen"])
                full_tree_runs.append({"records": records, "audit": audit})
                print(f"      VL={vl:<4} {audit['nodes_recorded']:>7} nodes "
                      f"(all)  {audit['seconds']:.1f}s", flush=True)
        runs.extend(full_tree_runs)

        # --- determinism self-check -------------------------------------
        # C3b asks for this to be pinned and C5 depends on it: the equivalence
        # configuration must be bit-deterministic across runs, or the golden
        # trees describe one run rather than the reference's behaviour. Re-runs
        # the first position at VL 2.5 and diffs the whole record list.
        determinism = None
        if not args.smoke:
            print("[determinism] re-running position 0 at VL=2.5", flush=True)
            mctsv4.VIRTUAL_LOSS = 2.5
            board = chess.Board(accepted[0]["fen"])
            repeat, _ = run_reference(mcts, board, args.sims, recorder,
                                      visited_only=True)
            original = next(r["records"] for r in runs
                            if r["audit"]["position"] == 0
                            and r["audit"]["virtual_loss"] == 2.5
                            and not r["audit"]["full_tree"])
            identical = (len(repeat) == len(original) and
                         all(a[:3] == b[:3] and a[5] == b[5] and
                             struct.pack("<d", a[3]) == struct.pack("<d", b[3])
                             for a, b in zip(repeat, original)))
            if not identical:
                print("ERROR: the equivalence configuration is NOT "
                      "bit-deterministic across runs; golden trees would be "
                      "unreproducible.", file=sys.stderr)
                return 1
            determinism = {"position": 0, "virtual_loss": 2.5,
                           "nodes": len(repeat), "identical": True}
            print(f"[determinism] identical over {len(repeat)} nodes",
                  flush=True)
    finally:
        mctsv4.VIRTUAL_LOSS = 2.5
        mcts.shutdown()

    # --- write ----------------------------------------------------------
    args.out_dump.parent.mkdir(parents=True, exist_ok=True)
    dump_stats = write_dump(args.out_dump, recorder)
    tree_stats = write_trees(args.out_trees, runs)

    manifest = {
        "provenance": {
            "generator": "tools/gen_gate1_golden.py",
            "generated_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "python": platform.python_version(),
            "python_build": sys.version,
            "platform": platform.platform(),
            "python_chess": chess.__version__,
            "numpy": np.__version__,
            "torch": torch.__version__,
            "device": str(device),
            "cuda_device": (torch.cuda.get_device_name(0)
                            if device.type == "cuda" else None),
            "model": str(args.model.relative_to(REPO_ROOT)),
            "model_sha256": sha256_of(args.model),
            "reference_sha256": sha256_of(REPO_ROOT / "core" / "mctsv4.py"),
            "seed": args.seed,
            "argv": sys.argv[1:],
        },
        "corpus": "quiet",
        "config": {
            "workers": 1,
            "cache_size": 1,
            "tablebase": False,
            "dirichlet": False,
            "canonical_order_patch": True,
            "virtual_losses": list(VIRTUAL_LOSSES),
            "sims": args.sims,
            "full_tree_sims": args.full_tree_sims,
            "max_tree_depth": mctsv4.MAX_TREE_DEPTH,
            "search_params": {
                "c_init": SearchParams().c_init,
                "c_base": SearchParams().c_base,
                "fpu_root": SearchParams().fpu_root,
                "fpu_tree": SearchParams().fpu_tree,
                "policy_temperature": SearchParams().policy_temperature,
            },
        },
        "positions": accepted,
        "rejected": rejected,
        "runs": [r["audit"] for r in runs],
        "dump": dump_stats,
        "trees": tree_stats,
        "determinism_check": determinism,
    }
    with open(args.out_manifest, "w", encoding="utf-8") as handle:
        json.dump(manifest, handle, indent=2)
        handle.write("\n")

    print()
    print(f"dump     {args.out_dump}  "
          f"{dump_stats['entries']} positions, {dump_stats['moves']} moves")
    print(f"trees    {args.out_trees}  "
          f"{tree_stats['runs']} runs, {tree_stats['nodes']} nodes")
    print(f"manifest {args.out_manifest}  "
          f"{len(accepted)} positions accepted, {len(rejected)} rejected")
    return 0


# ---------------------------------------------------------------------------
# C6 — the terminal corpus
# ---------------------------------------------------------------------------

def build_line(base_fen: str, moves: list[str]) -> chess.Board:
    """The root board for one spec: `base_fen` with `moves` legally played onto it.

    Every assertion here is a precondition of the corpus rather than a defensive
    habit. A base FEN that is not `is_valid()`, or a move that is not legal from
    where it is played, would put a position in the corpus that no game can
    reach — and the whole point of building the roots this way instead of writing
    them out is that the ep square of every position after the base is set by
    python-chess's own `push()`, i.e. by the raw rule the C++ side derives.
    """
    board = chess.Board(base_fen)
    if not board.is_valid():
        raise AssertionError(f"base FEN is not a legal position: {base_fen} "
                             f"({board.status()!r})")
    if board.ep_square is not None:
        raise AssertionError(
            f"base FEN {base_fen} names an en-passant square. Hand-written ep "
            f"fields are the one thing the C6 corpus must not contain -- see "
            f"DECISIONS.md, C3, on has_legal_en_passant.")
    for uci in moves:
        move = chess.Move.from_uci(uci)
        if move not in board.legal_moves:
            raise AssertionError(f"{uci} is not legal in {board.fen()} "
                                 f"(spec base {base_fen})")
        board.push(move)
    if board.is_game_over():
        raise AssertionError(f"root position is already over: {board.fen()}")
    if not any(board.legal_moves):
        raise AssertionError(f"root position has no legal moves: {board.fen()}")
    return board


def history_fens(board: chess.Board) -> list[str]:
    """The pre-root game history, as the FENs `build_repetition_history` walks.

    Exactly that function's loop: pop `min(halfmove_clock, plies)` moves and take
    each position on the way, most recent first. The ROOT is not included --
    `build_repetition_history` seeds its counter with the root separately, and so
    does the C++ `set_position`, so including it here would count it twice.

    `fen_of` rather than `Board.fen()`: the default writes the ep square only
    when a capture is legal, which would move token 66 and therefore the nn_key
    on the positions where the two rules differ. See DECISIONS.md, C2.
    """
    out: list[str] = []
    probe = board.copy()
    for _ in range(min(probe.halfmove_clock, len(probe.move_stack))):
        probe.pop()
        out.append(fen_of(probe))
    return out


def _run_terminal(args, model, device, recorder: Recorder) -> int:
    specs = TERMINAL_POSITIONS[:args.limit] if args.limit else TERMINAL_POSITIONS
    if args.only:
        wanted = {name.strip() for name in args.only.split(",") if name.strip()}
        unknown = wanted - {spec[0] for spec in specs}
        if unknown:
            print(f"ERROR: unknown spec name(s): {sorted(unknown)}", file=sys.stderr)
            return 1
        specs = [spec for spec in specs if spec[0] in wanted]
    print(f"terminal corpus: {len(specs)} specs")

    mcts = build_engine(model, device, cache_size=1)
    accepted: list[dict] = []
    runs: list[dict] = []
    default_max_depth = mctsv4.MAX_TREE_DEPTH

    try:
        for index, (name, categories, base_fen, moves, sims, max_depth) in enumerate(specs):
            if args.max_sims:
                sims = min(sims, args.max_sims)
            board = build_line(base_fen, moves)
            fen = fen_of(board)
            history = history_fens(board)
            print(f"[{index + 1}/{len(specs)}] {name:24s} {fen}", flush=True)
            print(f"{'':29s} categories={','.join(categories)} sims={sims} "
                  f"max_depth={max_depth} history={len(history)}", flush=True)

            # The reference reads MAX_TREE_DEPTH as a module global at every
            # descent step, so setting it here is how a depth-cap spec is run.
            # The C++ side reads SearchConfig.max_tree_depth, which the test
            # takes from this run's manifest entry.
            mctsv4.MAX_TREE_DEPTH = max_depth

            position_runs = []
            for vl in VIRTUAL_LOSSES:
                mctsv4.VIRTUAL_LOSS = vl
                records, audit = run_reference(mcts, board, sims, recorder,
                                               visited_only=True, strict=False)
                audit.update(virtual_loss=vl, sims=sims, full_tree=False,
                             position=index, name=name, fen=fen,
                             max_tree_depth=max_depth, categories=list(categories))
                position_runs.append({"records": records, "audit": audit})
                census = audit["census"]
                print(f"      VL={vl:<4} visits={audit['root_visits']:<5} "
                      f"nodes={audit['nodes_recorded']:<6} "
                      f"depth<={audit['max_depth']:<3} "
                      f"term={census['terminal_nodes']:<4} "
                      f"(win {census['terminal_win']}, draw {census['terminal_draw']}) "
                      f"draws={audit['draw_by_rule_hits']:<5} "
                      f"cap={census['at_depth_cap']:<4} "
                      f"early={audit['early_exit']!s:<5} "
                      f"best={audit['best_move']} {audit['seconds']:.1f}s",
                      flush=True)

            for run in position_runs:
                runs.append(run)
            accepted.append({"index": index, "name": name, "fen": fen,
                             "base_fen": base_fen, "moves": list(moves),
                             "history": history, "categories": list(categories),
                             "sims": sims, "max_tree_depth": max_depth})

        # --- full-tree control runs -------------------------------------
        # Same reasoning as the quiet corpus: the visited-subtree runs above say
        # nothing about UNVISITED children, whose priors and order are under
        # test. Four specs are re-run at a smaller budget recording every node.
        # The four are chosen across categories rather than by index, so the
        # control covers a mate, a stalemate, a repetition and a cap.
        full_tree_names = ("mate2-rooks-ladder", "stalemate-queen-h1",
                           "threefold-blocked-pawns", "depthcap-07")
        for spec in accepted:
            if spec["name"] not in full_tree_names:
                continue
            board = build_line(spec["base_fen"], spec["moves"])
            mctsv4.MAX_TREE_DEPTH = spec["max_tree_depth"]
            print(f"[full-tree] {spec['name']} at {args.full_tree_sims} sims", flush=True)
            for vl in VIRTUAL_LOSSES:
                mctsv4.VIRTUAL_LOSS = vl
                records, audit = run_reference(mcts, board, args.full_tree_sims,
                                               recorder, visited_only=False,
                                               strict=False)
                audit.update(virtual_loss=vl, sims=args.full_tree_sims,
                             full_tree=True, position=spec["index"],
                             name=spec["name"], fen=spec["fen"],
                             max_tree_depth=spec["max_tree_depth"],
                             categories=list(spec["categories"]))
                runs.append({"records": records, "audit": audit})
                print(f"      VL={vl:<4} {audit['nodes_recorded']:>7} nodes (all)  "
                      f"{audit['seconds']:.1f}s", flush=True)

        # --- determinism self-check -------------------------------------
        determinism = None
        if not args.smoke:
            # The LARGEST recorded tree, not the first position. The first is a
            # mate-in-one, where the short-circuit stops the reference at two
            # nodes — re-running that and finding it identical says almost
            # nothing. Determinism is a claim about a 5,000-simulation run, so it
            # is checked on one.
            biggest = max(
                (r for r in runs if not r["audit"]["full_tree"]),
                key=lambda r: r["audit"]["nodes_recorded"])
            target = next(spec for spec in accepted
                          if spec["index"] == biggest["audit"]["position"])
            print(f"[determinism] re-running {target['name']} at VL=2.5 "
                  f"({biggest['audit']['nodes_recorded']} nodes)", flush=True)
            mctsv4.MAX_TREE_DEPTH = target["max_tree_depth"]
            mctsv4.VIRTUAL_LOSS = 2.5
            board = build_line(target["base_fen"], target["moves"])
            repeat, _ = run_reference(mcts, board, target["sims"], recorder,
                                      visited_only=True, strict=False)
            original = next(r["records"] for r in runs
                            if r["audit"]["position"] == target["index"]
                            and r["audit"]["virtual_loss"] == 2.5
                            and not r["audit"]["full_tree"])
            identical = (len(repeat) == len(original) and
                         all(a[:3] == b[:3] and a[5:] == b[5:] and
                             struct.pack("<d", a[3]) == struct.pack("<d", b[3])
                             for a, b in zip(repeat, original)))
            if not identical:
                print("ERROR: the equivalence configuration is NOT "
                      "bit-deterministic across runs; golden trees would be "
                      "unreproducible.", file=sys.stderr)
                return 1
            determinism = {"position": target["index"], "virtual_loss": 2.5,
                           "nodes": len(repeat), "identical": True}
            print(f"[determinism] identical over {len(repeat)} nodes", flush=True)
    finally:
        mctsv4.VIRTUAL_LOSS = 2.5
        mctsv4.MAX_TREE_DEPTH = default_max_depth
        mcts.shutdown()

    # --- coverage -------------------------------------------------------
    # Measured, not declared. `categories` on a spec says what it was WRITTEN to
    # exercise; this counts what the reference actually did, and the two are
    # cross-checked here and again in tests/test_c6_gate1_full.py. A spec whose
    # intended class never fired is a spec that is not testing what it claims.
    coverage = {
        "checkmate_terminals": sum(r["audit"]["census"]["terminal_win"] for r in runs),
        "draw_terminals": sum(r["audit"]["census"]["terminal_draw"] for r in runs),
        "draw_by_rule_hits": sum(r["audit"]["draw_by_rule_hits"] for r in runs),
        "depth_cap_nodes": sum(r["audit"]["census"]["at_depth_cap"] for r in runs),
        "early_exits": sum(1 for r in runs if r["audit"]["early_exit"]),
        "terminal_with_children": sum(
            r["audit"]["census"]["terminal_with_children"] for r in runs),
    }
    missing = []
    if coverage["checkmate_terminals"] == 0:
        missing.append("no checkmate terminal in any run")
    if coverage["draw_terminals"] == 0:
        missing.append("no drawn terminal (stalemate / insufficient / rule) in any run")
    if coverage["draw_by_rule_hits"] == 0:
        missing.append("_draw_by_rule never fired (no threefold, no fifty-move)")
    if coverage["depth_cap_nodes"] == 0:
        missing.append("the depth cap never fired")
    if coverage["early_exits"] == 0:
        missing.append("the depth-1 mate short-circuit never fired")
    if missing:
        print("ERROR: the terminal corpus does not exercise what it claims:",
              file=sys.stderr)
        for line in missing:
            print(f"  {line}", file=sys.stderr)
        print("  Refusing to write golden data a test would then certify as "
              "covering C6.", file=sys.stderr)
        return 1

    # --- write ----------------------------------------------------------
    args.out_dump.parent.mkdir(parents=True, exist_ok=True)
    dump_stats = write_dump(args.out_dump, recorder)
    tree_stats = write_trees(args.out_trees, runs)

    manifest = {
        "provenance": {
            "generator": "tools/gen_gate1_golden.py --corpus terminal",
            "generated_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "python": platform.python_version(),
            "python_build": sys.version,
            "platform": platform.platform(),
            "python_chess": chess.__version__,
            "numpy": np.__version__,
            "torch": torch.__version__,
            "device": str(device),
            "cuda_device": (torch.cuda.get_device_name(0)
                            if device.type == "cuda" else None),
            "model": str(args.model.relative_to(REPO_ROOT)),
            "model_sha256": sha256_of(args.model),
            "reference_sha256": sha256_of(REPO_ROOT / "core" / "mctsv4.py"),
            "seed": args.seed,
            "argv": sys.argv[1:],
        },
        "corpus": "terminal",
        "config": {
            "workers": 1,
            "cache_size": 1,
            "tablebase": False,
            "dirichlet": False,
            "canonical_order_patch": True,
            "virtual_losses": list(VIRTUAL_LOSSES),
            "full_tree_sims": args.full_tree_sims,
            # The DEFAULT, i.e. the reference's own constant. Per-run overrides
            # live on each run's `max_tree_depth`, and the depth-cap specs are
            # the only ones that differ from this.
            "max_tree_depth": default_max_depth,
            "search_params": {
                "c_init": SearchParams().c_init,
                "c_base": SearchParams().c_base,
                "fpu_root": SearchParams().fpu_root,
                "fpu_tree": SearchParams().fpu_tree,
                "policy_temperature": SearchParams().policy_temperature,
            },
        },
        "positions": accepted,
        "rejected": [],
        "runs": [r["audit"] for r in runs],
        "coverage": coverage,
        "dump": dump_stats,
        "trees": tree_stats,
        "determinism_check": determinism,
    }
    with open(args.out_manifest, "w", encoding="utf-8") as handle:
        json.dump(manifest, handle, indent=2)
        handle.write("\n")

    print()
    print(f"dump     {args.out_dump}  "
          f"{dump_stats['entries']} positions, {dump_stats['moves']} moves")
    print(f"trees    {args.out_trees}  "
          f"{tree_stats['runs']} runs, {tree_stats['nodes']} nodes, "
          f"{tree_stats['terminal_nodes']} terminal")
    print(f"manifest {args.out_manifest}  {len(accepted)} positions")
    print(f"coverage {coverage}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
